explosion/thinc

thinc/linear/serialize.pyx, thinc/structs.pxd
changes SparseArrayC to a packed struct of platform independent size to match exactly the file format (minus byte order)
speeds up loading by about 2x
=> replace sequential fread() calls in Reader by a single read per row

setup.py
This bug is hidden because `termcolor` is listed in `requirements.txt`, used by travis, but not listed in `setup.py`. See below the `ImportError` on a fresh `pip install thinc`:
```
$ python
In [4]: import thinc.check
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-e97ab0d72623> in <module>()
----> 1 import thinc.check
/Users/rolando/miniconda3/envs/tmp-test/lib/python3.5/site-packages/thinc/check.py in <module>()
5 from numpy import ndarray
6
----> 7 from .exceptions import UndefinedOperatorError, DifferentLengthError
8 from .exceptions import ExpectedTypeError, ShapeMismatchError
9 from .exceptions import OutsideRangeError …
```
=> Fix termcolor dependency.

thinc/check.py, thinc/extra/eg.pyx, thinc/neural/ops.pyx
This mainly address Python 2.7's Windows interpreter where `numpy`'s
`shape` have `long` values and hence `isinstance(shape[i], int)`
returns `False`.
--
Related: https://github.com/numpy/numpy/issues/5809
=> Fix integer check on array shapes.

setup.py
Setup.py didn't run on cuda 9, fixed the proper compile options. This fix should also work on CUDA 8
=> Update setup.py to work with CUDA 9.0

examples/basic_tagger.py
The basic_tagger example doesn't seem to run out of the box.  It looks like a typo in the Import.  I've resolved this here and made a few other tidy ups.
basic_tagger is now running on my system.
=> Fixed basic_tagger example

thinc/extra/_vendorized/keras_generic_utils.py
The lack of space was triggering my OCD (and many others I suppose). 😄 
*Before:*
*After:*
I know it's a small thing, but anyway, here it is. :)
=> Add missing space in statement.

setup.py
This patch allows one to specify BLAS library on macOS and Windows too
```
export THINC_BLAS=/path/to/libmkl_rt.dylib
```
```
set THINC_BLAS=\path\to\mkl_rt.lib
```
=> Improve link command generation for THINC_BLAS

setup.py
Related to https://github.com/explosion/spaCy/pull/2998
I changed the variable names to be consistent with spaCy.
=> fix issue compiling the latest thinc on MacOS 10.3.6

requirements.txt, setup.py, thinc/exceptions.py
Keeps Thinc tidy and makes the code reusable and easier to maintain. See here:
https://github.com/ines/wasabi/blob/master/wasabi/traceback.py
=> Add traceback printer via wasabi

thinc/extra/_vendorized/keras_datasets.py
This doesnt follow the correct grammar of python, an 'except' is always
needed before an else in a try-except-else-finally statement.
=> Fix SyntaxError in try-except import cPickle Statement

thinc/neural/ops.pyx
Attempt to fix spaCy issue https://github.com/explosion/spaCy/issues/3880. The error in that issue is raised by `ops.pyx` on the line  `assert len(X) == 0` (https://github.com/explosion/thinc/blob/master/thinc/neural/ops.pyx#L138), and it happens when the tagger model is run with an empty doc as last element in a call to `nlp.pipe()`.
I think this happens because the `flatten` function adds one additional bit of padding at the end (https://github.com/explosion/thinc/blob/master/thinc/neural/ops.pyx#L119) which is not stripped away when `unflatten` removes the padding only when `length != 0` (https://github.com/explosion/thinc/blob/master/thinc/neural/ops.pyx#L136) for the last variable `length` in `lengths` (accessed outside of its `for` loop).
I don't have a proper way of testing this …
=> fix unflatten padding when last element is empty

examples/attention_tagger.py, examples/imdb_attention.py, examples/imdb_cnn.py, thinc/api.py, thinc/extra/load_nlp.py, thinc/neural/_classes/layernorm.py, thinc/neural/_classes/multiheaded_attention.py, thinc/neural/_classes/resnet.py, thinc/neural/ops.pyx, thinc/t2t.py
* Implement backprop of softmax
* Replace PyTorch mask with our mask function
* Add matmul op, to remove calls to numpy.matmul
The layer would mostly be usable in spaCy now, although the padding is problematic if the sequences are long. The implementation is about 2-3x faster than the previous, on CPU.
=> Remove PyTorch and numpy calls from multi-headed attention

thinc/neural/ops.pyx
Addressing an issue in spaCy around ngrams (Issue https://github.com/explosion/spaCy/issues/3611), I found a line in `ops.pyx` that could allocate negative lengths, e.g. when allocating 2-grams for a 1-token doc it would try to allocate `(1-2,)` shape.
Setting to min threshold 0 fixes the bug.
=> avoid allocating a negative shape

thinc/check.py, thinc/exceptions.py, thinc/neural/ops.pyx
Since Python version 3.3, Collections Abstract Base Classes have been moved to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.7. Subsequently, they will be removed entirely.
(source: https://docs.python.org/3/library/collections.html)
Related to issue #108
=> Fix Collections Abstract Base Classes imports for Python 3.8

azure-pipelines.yml, requirements.txt, setup.py, thinc/about.py, thinc/neural/ops.pyx
* Allow read-only numpy arrays
* Update to blis v0.4.0
Note that read-only arrays means the new version won't work with the prior version of `cython-blis`, because only blis v0.4.0 supports read-only arrays. Even if the user *isn't* passing read-only arrays, they'll be marked as possibly read-only by the type-system, so we'll get an error if we try to pass them to a function which says they might be modified. Basically it's like const: if we want to be const-correct, we need the library we're calling into to be const-correct too.
=> Update to blis v0.4.0

thinc/check.py, thinc/neural/ops.pyx
Just like #109 , but (hopefully) without bug, and applied to master branch.
Since Python version 3.3, Collections Abstract Base Classes have been moved to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.7. Subsequently, they will be removed entirely.
(source: https://docs.python.org/3/library/collections.html)
Related to issue #108
=> use collections.abc when possible

setup.py
Currently `cupy-cuda110` does not exist.
https://docs-cupy.chainer.org/en/latest/install.html#install-cupy
https://pypi.org/project/cupy-cuda101/
=> CuPy package for CUDA 10.1 is `cupy-cuda101`

setup.py
I think this is a typo but wanted to make sure. `cupy` has a different version of CUDA 10.1 and therefore unable to run `thinc[cuda101]`.
=> Fix cupy to cuda 10.1 version

thinc/check.py, thinc/neural/_classes/model.py, thinc/tests/unit/test_model.py
Make old/saved Model operators thread-local, too. Doesn't seem like a particularly great solution, but seems to least temporarily fix https://github.com/explosion/spaCy/issues/4349. I think better solutions would require a fairly major restructuring of `Model`.
=> Make Model operators and device ops thread-local

azure-pipelines.yml, docs/config.md, requirements.txt, setup.py, thinc/__init__.py, thinc/_registry.py, thinc/config.py, thinc/i2v.py, thinc/misc.py, thinc/neural/_classes/embed.py, thinc/neural/optimizers.pyx, thinc/t2t.py, thinc/t2v.py, thinc/tests/test_config.py, thinc/v2v.py
With the move to use [catalogue](https://github.com/explosion/catalogue) for extended configuration in spaCy, we need a solution for configuration management. It makes sense for the solution to live in Thinc, because Thinc's optimizers, layers etc should all work with the config management.
I looked closely at all of the options for config management. The config files will get pretty big, so we shouldn't just use JSON. YAML is terrible. XML would work but it'll involve a fair bit of code. TOML and HCL don't have first-part support in Python, and they're a bit less common.
I'm proposing a solution based on Python's configparser module, with a couple of small conventions. 
Configparser's format is an ini-like format that maps into a two-level dict:
```
[outer key 1]
inner key 1a = 1
inner …
```
=> Add Config class

azure-pipelines.yml, requirements.txt, setup.py, thinc/_registry.py, thinc/config.py, thinc/extra/wrappers.py, thinc/i2v.py, thinc/misc.py, thinc/neural/optimizers.pyx, thinc/t2t.py, thinc/tests/test_config.py, thinc/tests/unit/test_registry.py, thinc/v2v.py
* Add pydantic as a dependency
* Implement validation and default filling for the config system
* Add a few type declarations to some registry functions
* Remove Python2.7 and 3.5 from the classifiers and build system
=> Use pydantic to fill config defaults. Drop old Pythons

thinc/describe.py, thinc/neural/_classes/model.py
Classes usually define their dimension, gradients and parameter
attributes using the @describe.attributes class decorator. This
decorator attaches descriptor objects to the class, allowing some
indirection features such as late definintion of dimensions.
The previous implementation was confusing, because important logic was
implemented within the descriptors, instead of on the Model class. This
PR refactors that logic into the Model class, and has the descriptors
delegate into those methods.
The new methods on Model are:
model.{has, get, set}_{dim, param, grad}()
model.has_dim(name: str) -> bool: Whether the model has that dimension
model.get_param(name: str) -> array: Get the parameter.
model.set_grad(name: str, value: array) -> None: Set the gradient.
=>  Refactor dims, grads and params system

thinc/describe.py, thinc/neural/_classes/affine.py, thinc/neural/_classes/embed.py, thinc/neural/_classes/feed_forward.py, thinc/neural/_classes/function_layer.py, thinc/neural/_classes/layernorm.py, thinc/neural/_classes/maxout.py, thinc/neural/_classes/mish.py, thinc/neural/_classes/model.py, thinc/neural/util.py, thinc/tests/integration/test_feed_forward.py, thinc/tests/unit/test_affine.py, thinc/tests/unit/test_model.py, thinc/wire.py
The `Model` class supported some weird features with class attributes, using the description system. This PR cleans the unnecessary stuff up.
We no longer have `on_init_hooks`, and `on_data_hooks` is removed as a descriptor -- instead it should just be set in the model `__init__` function.
We also add a `model.infer_dimensions` method, to allow clearer calls if that's what the code is trying to do.
=> Remove unnecessary "hooks" stuff from Model

thinc/extra/wrappers.py, thinc/neural/_classes/affine.py, thinc/neural/_classes/attention.py, thinc/neural/_classes/convolution.py, thinc/neural/_classes/difference.py, thinc/neural/_classes/embed.py, thinc/neural/_classes/feature_extracter.py, thinc/neural/_classes/feed_forward.py, thinc/neural/_classes/function_layer.py, thinc/neural/_classes/hash_embed.py, thinc/neural/_classes/layernorm.py, thinc/neural/_classes/maxout.py, thinc/neural/_classes/mish.py, thinc/neural/_classes/model.py, thinc/neural/_classes/multiheaded_attention.py, thinc/neural/_classes/relu.py, thinc/neural/_classes/resnet.py, thinc/neural/_classes/rnn.py, thinc/tests/integration/test_affine_learns.py, thinc/tests/unit/test_affine.py, thinc/tests/unit/test_pytorch_wrapper.py, thinc/tests/unit/test_rnn.py, thinc/wire.py
This is a pretty pervasive breaking change. Previously we had the following in our models:
Y, backward = model.begin_update(X)
dX = backward(dY, sgd=optimizer)
After this PR, we'll have this instead:
Y, backward = model.begin_update(X)
dX = backward(dY)
model.finish_update(sgd)
There are a number of reasons why the old way was bad. One is that we were changing the weights in the middle of the backward pass, which could introduce some nasty problems, especially when you had architectures with the same model instance twice. It also made it harder to divide up sub-batches, and just generally complicated the design (it made the signatures really ugly, for instance).
=> Remove sgd argument from backward callback

thinc/neural/_murmur3.cu
Fixes #128 : [`test_hash_gives_distinct_keys[CupyOps]`](https://github.com/explosion/thinc/blob/master/thinc/tests/unit/test_ops.py#L30) stops failing
Fixes https://github.com/explosion/spaCy/issues/4758: no more weird POS & dep tags
Probably fixes https://github.com/explosion/spaCy/issues/4816 (should be tested after merge)
The murmur hash calculation for Windows (when using GPU/CUDA) was not working properly.
I finally figured out why: `int64_t` was being defined as `long int`. This is correct on LINUX, but not on [Windows](https://docs.microsoft.com/en-us/cpp/c-runtime-library/standard-types?redirectedfrom=MSDN&view=vs-2019).
So I added a bit of code to do some byte-size checking upfront and only then define the correct types. It's a little ugly, but I couldn't get this implemented in …
=> Fix murmur hash for GPU/Windows

thinc/backends/cupy_ops.py, thinc/layers/pytorchwrapper.py, thinc/layers/residual.py, thinc/model.py, thinc/shims/__init__.py, thinc/shims/pytorch.py, thinc/shims/shim.py, thinc/tests/integration/test_basic_tagger.py, thinc/tests/integration/test_roundtrip_bytes.py, thinc/tests/unit/test_affine.py, thinc/tests/unit/test_mem.py, thinc/tests/unit/test_pytorch_wrapper.py, thinc/util.py
Introduce specific support for having a model contain a non-Thinc model. This is better than storing the model in the generic `_attrs`, because we want to make sure we pass along calls to optimization and other parameter-relevant operations to the external models. Without a notion of these external models, we'll need each interface to be a special subclass of `Model`.
The "shims" system introduces a new base class, `Shim`, which interfaces to third-party packages should subclass. The `Shim` API is pretty small: you basically just have to make your class serializable with to/from bytes/disk methods, and you need to implement a `__call__` function that returns the output and the backprop callback. There are a couple of other methods as well, e.g. to cpu/gpu. Shims are stored within …
=> Introduce 'shims' package, fix PyTorchWrapper

thinc/config.py, thinc/model.py
- adding type for `operators` in `Model.define_operators`
- I think `Config` should get as `data` a `dict` object or a `ConfigParser` ? Or is there also a use-case where a `Config` parser itself is given as argument? (and would this not be caught already because `Config` inherits from `dict` ?) Either way a change is needed because `Config.from_str` calls `interpret_config` with a `ConfigParser`.
=> Small type fixes

setup.cfg, thinc/_registry.py, thinc/config.py, thinc/tests/unit/test_registry.py
=> Small refactor of config and registry parsing methods

.gitignore, thinc/model.py, thinc/tests/unit/test_model.py
Noticed two gaps in the `Model` API when preparing the `ray_parallel` example and starting to prepare a spaCy branch for the new Thinc.
**Gap 1: Node references** In spaCy, we often want to fetch some named sublayer of a network later. This comes up especially often with the `tok2vec` layers, but it can happen for other stuff as well (for instance, you might want to note the output layer separately or something). In previous Thinc, we just blindly banged the new attribute onto the instance, like `model.tok2vec = tok2vec`.
This PR adds another attribute, `_refs`, with `get_ref/set_ref/has_ref` methods to interface for it. You can also pass `refs` into the constructor. There's also a method `remove_node` that walks over the tree, and removes removes a node from any `layers` lists that …
=> Extend Model API (node references, dim/param/grad names properties)

thinc/backends/numpy_ops.pyx, thinc/layers/__init__.py
`CauchySimilarity` was missing from the imports in `layers.init`, causing trouble in spaCy imports.
Also reformated the formula for calculating output size after adding context from a window, I thought the spacing was confusing...
=> add cauchysimilarity import

thinc/api.py, thinc/config.py, thinc/layers/__init__.py
When running a config file through validation, the current code would show a tabular format of errors from Pydantic, but without specifying where exactly in the config they came from:
```
Config validation error
args                 field required
kwargs               field required
depth                extra fields not permitted
embed_size           extra fields not permitted
maxout_pieces        extra fields not permitted
pretrained_vectors   extra fields not permitted
width                extra fields not permitted
window_size          extra fields not permitted
```
This PR changes that into: 
```
Config validation error
nlp.pipeline.tok2vec.model   args                 field required
nlp.pipeline.tok2vec.model   kwargs               field required
nlp.pipeline.tok2vec.model   depth …
```
=> Track origin of ConfigValidationError

thinc/layers/chain.py, thinc/layers/concatenate.py
Changed the signature for `concatenate()` to `*layers: Model` instead of using a `List`, to allow using the operator in cases like `prefix | suffix`. The current version gave the error 
> concatenate() takes 1 positional argument but 2 were given
=> fix input type for concatenate to support "a | b"

README.md, thinc/config.py, thinc/tests/test_config.py, thinc/tests/util.py
```ini
[config]
@schedules = "my_cool_schedule.v1"
__args__ = [10, 16, 31]
final = 20
```
```python
@thinc.registry.schedules("my_cool_schedule.v1")
def my_cool_schedule(*steps: int, final: int = 10):
yield from steps
while True:
yield final
```
=> Fix up config/registry API and get coverage to 100%

thinc/config.py, thinc/tests/test_config.py
I'm pretty certain there's a bug in parsing recursive objects in thinc's `_fill` function on the current `develop` branch. I ran into it while testing from spaCy, so I tried creating a minimal example for testing here in `test_config.py`, avoiding generators and iterators etc for simplicity.
It looks like an object within an object is not returned properly. I tried debugging with this example. The `my_cool_repetitive_schedule.v1` creates the correct `learn_rate` object `[0.001, 0.001, 0.001, 0.001]` which is correctly [stored](https://github.com/explosion/thinc/blob/develop/thinc/config.py#L226) in `validation[key]`. But then when the recursive loop goes on to fill in `my_cool_optimizer.v1`, it doesn't have access to that object anymore, and fills in the original json `{'@schedules': …
=> WIP: Trouble with recursive objects in config

thinc/layers/concatenate.py, thinc/layers/hashembed.py, thinc/layers/maxout.py, thinc/model.py, thinc/tests/test_serialize.py
1. Model/layer names in error msg helps debugging
2. Ensure HashEmbed has a default `None` `nI` dimension
3. Throw an error when a none-`None` dimension is set to a different value (this shouldn't really happen, right ?)
=> Friendly debugging errors

thinc/config.py, thinc/types.py
Registered functions were becoming type-opaque, because of the registry decorator. Even after adding type annotations in catalogue, there were still problems getting it to work properly, because we assign the decorator to a class variable, which makes things that much more opaque to mypy.
I tried a few approaches, but it's complicated having an interaction between the type variable and the class. I don't really know what's going on but it complained of some sort of ambiguity.
My solution is to use a "protocol" to define a new type, `Decorator`. We can then declare the variable to be of that type when we assign it. This works! I even got a type error in my transformers script.
There's still some tricks to be solved with the `chain` operator. Not sure what's up but I don't always get type …
=> Add Decorator type to fix registry functions

thinc/layers/chain.py, thinc/layers/maxout.py, thinc/model.py
- The initialization of `chain` would throw an error if the underlying layer didn't not properly handle `predict(None)`, so preventing that here for robustness.
- `maxout` had a bug in its backprop function: the value to increment `b` needs to be reshaped to `(nO, nP)` (right?)
- Raising an informative error when these sort of wrong shapes occur in `inc_grad`
=> Fixing chain ini and maxout backprop

examples/howto/type_chain.py, thinc/layers/__init__.py, thinc/layers/chain.py, thinc/layers/clone.py, thinc/layers/dropout.py, thinc/layers/maxout.py, thinc/layers/mish.py, thinc/layers/pytorchwrapper.py, thinc/layers/relu.py, thinc/layers/softmax.py, thinc/tests/layers/test_combinators.py
Getting the `chain` operator to validate well is pretty tough. It seems mypy doesn't really support variable args: I can't get it to branch the type-logic on `len(args)`. Here's a hack that works in the meantime -- hopefully a new version of mypy will add support for what we need.
Instead of conditioning on the length of the variable, we can define a bunch of optionals, and condition on *those*. I've added support for up to 10, with the remaining backing off.
This gives a (pretty cryptic) type error on a broken model. The return type still isn't right though.
I think the right response here is "thanks I hate it". But at least we'll be able to make this work? Hopefully we can engage with mypy and get a better solution.
=> Improve type-checking for chain

thinc/config.py, thinc/initializers.py, thinc/loss.py, thinc/tests/test_config.py, thinc/tests/test_initializers.py, thinc/tests/test_loss.py, thinc/util.py
Specifying the default settings for those functions in the config makes sense and is consistent – but we can't actually call the functions, since they take data. In those cases, the loaded config returns a partial function.
=> Add partial registry functions for losses and initializers

thinc/layers/chain.py, thinc/tests/layers/test_feed_forward.py
In `chain.initialize`, we were assuming that the last last would be the one which needs the output dimension set by the variable `Y`. In fact arbitrary output layers might be set at the end.
The implementation is still pretty hacky here, and there will still be some problems. But at least I have an idea for how this should work:
We should tell people that if their layer doesn't register an `nO` dimension, `chain` is allowed to assume the layer input will be valid output. We use this to ignore layers like `dropout` and `LayerNorm` when inferring shapes.
We would still have some problems with the layers like `list2ragged`, `padded2list` etc. Shape inference past these layers could be possible in theory, but I don't currently see how to do it. I guess we would need to split things up a bit, …
=> Improve inference of output shape

thinc/model.py
Fix model (de)serialization:
- `int` has a `to_bytes(length, ...)` method so we need to prevent calling that one
- `data["refs"]` was not parsed correctly in `from_bytes`
=> fix model serialization

thinc/layers/uniqued.py, thinc/tests/layers/test_uniqued.py
There was a small long-standing bug in the backprop, that was masked by the fact that previously we returned `None` from most embedding layers' backprop, so we never actually called the un-unique.
I've also used a newer style from Hypothesis in this test. The old Hypothesis API was pretty tough, but this new one is very promising. I hope we can use it more in future for correctness tests, where we need a lot of examples.
=> Test and fix uniqued layer

thinc/layers/tensorflowwrapper.py, thinc/tests/layers/test_tensorflow_wrapper.py
This adds misc fixes/features to the thinc tensorflow shim/wrapper to support Mathy's keras models.
Changes:
=> TensorflowWrapper changes to support mathy model

thinc/model.py, thinc/shims/tensorflow.py, thinc/tests/layers/test_tensorflow_wrapper.py
=> Fix TensorFlow shim and tests

thinc/backends/__init__.py, thinc/backends/_param_server.py, thinc/model.py, thinc/optimizers.pyx, thinc/shims/pytorch.py, thinc/shims/shim.py, thinc/shims/tensorflow.py, thinc/tests/backends/test_mem.py, thinc/tests/layers/test_feed_forward.py, thinc/tests/layers/test_linear.py, thinc/tests/layers/test_lstm.py, thinc/tests/model/test_model.py
The `Memory` class was pretty dusty: it was pretty much unchaged since previous Thinc, and a lot of the details didn't really make sense. It was also not a JIT-friendly design, hindering future Jax adoption.
I've introduced a much simpler `ParamServer` object, and also improved the serialization and copy-to-device methods (since these were affected by the previous `Memory` class details). I've also phrased more things in terms of the `Model` public API, avoiding the internals pretty much everywhere.
There aren't really many changes to outward behaviour here, but there are a couple.
* `Model.__init__` drops the `grads` argument. It's not necessary, if something wants to set a grad they can do it after the model is constructed.
* The `Shim` class's `to_cpu` and `to_gpu` methods are replaced …
=> Replace Memory class, improve serialization format

thinc/optimizers.py
PR #218 introduced a bug: when calling `ops.adam()` with a parameter of dimension >1, it would crash with the error
> self.ops.adam(weights, gradient, mom1, mom2, b1, b2, eps, lr * lr_scale)
> File "thinc\backends\numpy_ops.pyx", line 338, in thinc.backends.numpy_ops.NumpyOps.adam
> ValueError: Buffer has wrong number of dimensions (expected 1, got 2)
I'm assuming this is because before that PR, `Memory`  stored the parameters as long arrays that could be passed as such to  `ops.adam()`, but now they require reshaping first.
=> reshape weights and gradient before calling ops.adam

thinc/layers/maxout.py, thinc/layers/mish.py, thinc/layers/relu.py
Pass `nI` as the previous layer's `nO`. Had a case where the dimension remained unset if I didn't do this (perhaps also pointing to an issue with dimension inference?). Either way - this makes the code more robust.
=> Pass nI to LayerNorm

thinc/config.py, thinc/model.py, thinc/optimizers.py, thinc/tests/layers/test_linear.py, thinc/tests/layers/test_lstm.py, thinc/tests/test_optimizers.py
As discussed with @honnibal:
* remove lookahead and related code
* make `Optimizer.__call__` take arguments `key, weights, gradient` (instead of making `key` a required keyword argument)
Also tidy up and add tests.
=> Refactor / update optimizers

thinc/layers/concatenate.py
Add in support for concatenating lists in the `concatenate` layer.
This works, as tested with spaCy. Before we had to do 
`concatenate_lists(CharacterEmbed(....), FeatureExtracter(...)`
now just `concatenate` works (without messing up the normal `concatenate` cases)
=> Have concatenate support lists

thinc/backends/cupy_ops.py, thinc/backends/ops.py, thinc/model.py
There was one spot where the cupy function call wasn't yet rewritten to `**dtype`.
Also added a more user-friendly warning in `Model.from_bytes` to point to incompatible versions (bound to happen).
=> small bugfix in cupy asarray

thinc/layers/concatenate.py
Only set the `chain` model's `nO` dim if all the chained layers have an `nO` set. Popped up in a test with spaCy.
=> Fix setting chained model's output dimension

thinc/layers/chain_module.py, thinc/optimizers.py
Inferring output shapes is kind of tricky, but it's also really nice if we can get it to work. Previously we used a very complicated approach, based on a sort of bidirectional inference. We tried to set shapes from the end of the network, and from the front, and sort of hoped it worked out.
Instead, this PR goes with a simpler heuristic that's easy to explain, which hopefully will be easier to program against:
If a layer has an unset `nO` dimension, it receives the `Y` variable passed in to `chain.initialize()`. This means that you can leave `nO` dimensions unset if they can be inferred from the eventual output. If reading the `nO` dimension from the model output would leave to an incorrect result (for instance if there's a shape transformation at the end), you'll need to specify the `nO` …
=> Improve chain.initialize() output shape inference

thinc/layers/concatenate.py
In spaCy, `test_tok2vec_configs` was failing on calling `backprop(vectors)` because of the recent changes to `concatenate`. I reverted part of the edits from [here](https://github.com/explosion/thinc/commit/4d32ac32e165f425fb30c69281c4dd0dda142c72#diff-5be155357e784dde8a496aa6aad6771fL74), and that seems to fix it. I'm not sure why this got removed in the first place though.
=> restore some edits from concatenate

examples/mnist.py, thinc/backends/ops.py, thinc/types.py
It's really nice to have batches generated, rather than precomputed, because this reduces the time-to-error in a lot of debugging loops. However, it also sucks to have to pass around the size, e.g. for progress bars. Having to rebatch and reshuffle every loop sucks too.
This PR suggests a low-code solution that addresses the problems, but maybe doesn't minimise surprise. We wrap the generator in a `SizedGenerator` type, which we pass a generator function. The `SizedGenerator` knows its length, and each time it is invoked it calls its function, allowing it to repeat over the data.
=> Slightly magical minibatching

thinc/api.py, thinc/backends/__init__.py, thinc/layers/tensorflowwrapper.py, thinc/model.py, thinc/shims/__init__.py, thinc/shims/shim.py, thinc/shims/tensorflow.py, thinc/tests/layers/test_tensorflow_wrapper.py, thinc/tests/model/test_model.py, thinc/util.py
- add `get_thread_state` helper for backends. When called it will get the thread local for the current thread, or create it from the global state attributes.
- After some searching I found a blog post that talked about a subtle detail that meant you cannot do mutable thread local data without subclassing threading.local. Update model operators thread local to use a subclass. This prevents errors in the overloaded operators test.
Source: http://slinkp.com/python-thread-locals-20171201.html
=> Fix errors using TensorFlowWrapper for multithreaded training

thinc/optimizers.py
Another fix from @honnibal - I'm just the messenger / tester :-)
The `adam` function requires a 1D array, so https://github.com/explosion/thinc/commit/912a2acca1b0fddbf20eadee77c27c2093a8748d introduced a bug that made spaCy quite unhappy.
=> ensure adam is called with 1D arrays

thinc/backends/jax_ops.py, thinc/backends/ops.py, thinc/layers/concatenate.py, thinc/layers/embed.py, thinc/layers/expand_window.py, thinc/layers/featureextractor.py, thinc/layers/hashembed.py, thinc/layers/linear.py, thinc/layers/list2array.py, thinc/layers/list2ragged.py, thinc/layers/maxout.py, thinc/layers/mish.py, thinc/layers/multisoftmax.py, thinc/layers/reduce_sum.py, thinc/layers/relu.py, thinc/layers/remap_ids.py, thinc/layers/residual.py, thinc/layers/softmax.py, thinc/layers/staticvectors.py, thinc/layers/strings2arrays.py, thinc/layers/uniqued.py, thinc/layers/with_array.py, thinc/layers/with_flatten.py, thinc/layers/with_padded.py, thinc/layers/with_ragged.py, thinc/model.py
`Model.ops` was incorrectly typed as `Union[NumpyOps, CupyOps]`, which meant that a variety of type issues went unnoticed.
=> Fix model.ops type and related issues

thinc/config.py, thinc/layers/dropout.py, thinc/layers/sparselinear.pyx, thinc/layers/with_getitem.py, thinc/model.py, thinc/tests/layers/test_layers_api.py, thinc/tests/layers/test_linear.py, thinc/tests/layers/test_lstm.py, thinc/tests/model/test_validation.py, thinc/tests/test_serialize.py, thinc/types.py, thinc/util.py
* implement validation in `Model.initialize` where we care less about the extra overhead and have data samples available
* validate the inputs and outputs against the type annotations of the `forward` function (`X` and return type)
* I xfailed the LSTM test that currently causes a validation error (mismatched dimensions, I think). Not sure if this is a problem with the test, the implementation or the validation.
* pydantic raises a `RuntimeError` if it comes across a `Tuple` annotation, so I've changed those occurences to `Tuple[Any, ...]`, which should be equivalent
* Cython really doesn't like any generic annotations if we want the function to be bound (so it becomes inspectable and isn't treated like a builtin)
* needs more tests
=> WIP: add runtime data validation

requirements.txt, setup.cfg, thinc/backends/__init__.py, thinc/layers/staticvectors.py, thinc/model.py, thinc/tests/model/test_model.py, thinc/util.py
:arrow_up: Replace thread locals with contextvars.
This would allow using Thinc in scenarios that are not purely thread-based, like `asyncio` (e.g. in FastAPI apps). While still working the same for thread-based scenarios.
From PEP 567: https://www.python.org/dev/peps/pep-0567/#backwards-compatibility
> This proposal preserves 100% backwards compatibility.
> 
> Libraries that use threading.local() to store context-related values, currently work correctly only for synchronous code. Switching them to use the proposed API will keep their behavior for synchronous code unmodified, but will automatically enable support for asynchronous code.
---
Python docs: https://docs.python.org/3/library/contextvars.html
PEP 567 "Converting code that uses threading.local()": …
=> Replace thread locals with contextvars

thinc/api.py, thinc/layers/__init__.py, thinc/layers/with_debug.py, thinc/tests/layers/test_with_debug.py
Wraps any layer and can be called with 3 optional callbacks: `on_init`, `on_forward` and `on_backprop`, which receive the same arguments as the functions they're called in. Can be used to log stuff, inspect inputs/outputs, benchmark etc.
=> Add with_debug layer

thinc/backends/ops.py, thinc/initializers.py, thinc/layers/embed.py, thinc/layers/hashembed.py, thinc/layers/staticvectors.py, thinc/model.py, thinc/optimizers.py, thinc/tests/layers/test_lstm.py, thinc/tests/model/test_model.py, thinc/types.py
* Add `dropout_rate` attr to `HashEmbed`, `Embed` and `StaticEmbed` layers. Dropout is applied by creating one dropout mask vector for the whole batch, and applying it.
* Change `Dropout` layer to use the attr name `dropout_rate`, rather than `rate`.
* Change the `set_dropout_rate` helper to just look for the attr name, rather than the nodes.
* Remove traces of spaCy from the `StaticVectors` table. Instead expect vectors as an array, and wrap it in an arbitrary object to prevent msgpack serialization.
=> Support dropout in embedding layers

thinc/model.py
:fire: Remove model's ThreadState class, as it's replaced with context vars and is no longer used.
=> Remove model's ThreadState class, no longer used

examples/01_intro_model_definition_methods.ipynb, examples/02_transformers_tagger_bert.ipynb, examples/transformers_tagger.py, thinc/backends/ops.py, thinc/layers/dropout.py, thinc/layers/embed.py, thinc/layers/expand_window.py, thinc/layers/featureextractor.py, thinc/layers/hashembed.py, thinc/layers/multisoftmax.py, thinc/layers/pytorchwrapper.py, thinc/layers/remap_ids.py, thinc/layers/staticvectors.py, thinc/layers/tensorflowwrapper.py, thinc/layers/uniqued.py, thinc/layers/with_array.py, thinc/layers/with_getitem.py, thinc/model.py, thinc/tests/layers/test_linear.py, thinc/tests/layers/test_pytorch_wrapper.py, thinc/tests/layers/test_tensorflow_wrapper.py, thinc/tests/layers/test_uniqued.py, thinc/tests/model/test_jax_model.py, thinc/tests/model/test_model.py, thinc/tests/test_serialize.py
As discussed:
* make `Model.attrs` a dict and a property to allow assigning to it directly
* remove `Model.get_attr`, `Model.set_attr`, `Model.has_attr`, `Model.attr_names`
=> Simplify Model attrs

thinc/tests/backends/test_ops.py, thinc/tests/model/test_validation.py
Two small fixes, ensuring all tests run on GPU :-)
Though `test_backprop_reduce_sum` feels a little flakey. I think perhaps raising the tolerance level helped, as I haven't been able to make it fail anymore, but let's see in the future.
=> Fixing unit tests with GPU

examples/06_predicting_like_terms.ipynb
- I thought it was suspicious that it trained to 98% accuracy, and it turns out I was right! :sob:
- the dataset included a constant 10 noise terms in its expressions, and the model seemed to be learning to count terms and subtract 10. Maybe it only learned to count " + "?
- update dataset to remove one-hot encoding after review with @honnibal
- add model defaults that can train to ~80% accuracy if given 100 or more epochs.
- add intermediate exercise to improve the model training performance by tweaking the architecture.
Related to: #258
=> Example: fix predict like terms dataset

requirements.txt, setup.cfg, thinc/config.py, thinc/layers/chain.py, thinc/optimizers.py, thinc/tests/test_config.py
We still need to leave in the `Generator` workarounds in the config to prevent consuming generators if they're part of a union with `Iterator`. But we get to remove the ugly hacks around the generics.
=> Update to Pydantic v1.4

thinc/layers/dropout.py, thinc/tests/layers/test_linear.py, thinc/tests/model/test_model.py
PR https://github.com/explosion/thinc/pull/266 didn't actually change the `attr` name of the `Dropout` layer from `rate` to `dropout_rate`, which meant that `set_dropout_rate` didn't work anymore.
=> fix rename to dropout_rate

thinc/layers/featureextractor.py
I'm not sure this is the "fix" we want, but the current `docs` type in `FeatureExtractor.forward()` does not match with the `begin_training(X=...)` arguments we're giving in spaCy, making the unit tests fail if we type it as `List[Doc]`. 
I don't think I know the historic trail here, and why we're also having this check of `if hasattr(doc, "to_array")` in this layer. Could be that the type should be as currently stated, and we need to refactor elsewhere? I'm not sure.
=> Remove type from fwd in FeatureExtractor

azure-pipelines.yml, setup.cfg, thinc/api.py, thinc/layers/__init__.py, thinc/layers/mxnetwrapper.py, thinc/shims/__init__.py, thinc/shims/mxnet.py, thinc/tests/layers/test_mxnet_wrapper.py, thinc/util.py
Add support for wrapping MXNet models:
```python
from thinc.api import MXNetWrapper
import mxnet as mx
mx_model = mx.gluon.nn.Sequential()
mx_model.add(
mx.gluon.nn.Dense(n_hidden),
mx.gluon.nn.LayerNorm(),
mx.gluon.nn.Dense(n_hidden, activation="relu"),
mx.gluon.nn.LayerNorm(),
mx.gluon.nn.Dense(10, activation="softrelu"),
)
thinc_model = MXNetWrapper(mx_model)
X = thinc_model.ops.alloc2f(1, 784)
Y = thinc_model.predict(X)
assert list(Y.shape) == [1, 10]
```
=> Feature: MXNet shim

thinc/tests/mypy/test_mypy.py
:green_heart: Use `site` (site-packages) to detect how to run mypy tests.
This should allow running tests in CI with the package installed:
```console
$ python -m pytest --pyargs thinc --cov=thinc --cov-report=xml
```
But also with source code without having to install it first:
```console
$ pytest thinc
```
This supersedes #247
=> Use site (site-packages) to detect how to run mypy tests

examples/00_intro_to_thinc.ipynb
If you run the [00_intro_to_thinc.ipynb](https://github.com/explosion/thinc/blob/master/examples/00_intro_to_thinc.ipynb) notebook on a GPU, you get the following error when you execute the cell where you create an optimizer and do several passes over the data.
```
TypeError                                 Traceback (most recent call last)
<ipython-input-27-c7aae9724b89> in <module>()
21         total += Yh.shape[0]
22     score = correct / total
---> 23     print(f" {i} {score:.3f}")
TypeError: unsupported format string passed to cupy.core.core.ndarray.__format__
```
Also see the related open NumPy issue: [ndarray should offer `__format__` that can adjust precision #5543 ](https://github.com/numpy/numpy/issues/5543).
This pull request proposes a simple fix/workaround.
=> String formatting precision fails when run on GPU.

thinc/model.py
Oops, we were converting the model dict to numpy, then passing `self.to_dict()` to `convert_recursive` instead of the converted numpy array 😅
=> fix issue where GPU model couldn't be serialized

thinc/optimizers.py, thinc/tests/layers/test_basic_tagger.py
* `__slots__ ` for `Optimizer`
* Pass on the value of `use_averages` consistently instead of overwriting
* Have `L2_is_weight_decay` as a parameter for `RAdam`
=> Small fixes for the optimizers

thinc/layers/concatenate.py, thinc/layers/staticvectors.py, thinc/types.py
This was a cute little bug:
* `Unserializable` has a `data` field
* `StaticVectors` expects a `vectors` argument (e.g. spaCy's `Vectors` object) that has a `data` field
* So you'd need to do `model.attrs["vectors"].data.data` to get to the actual data, but I renamed it instead to avoid future confusion
=> Rename Unserializable 'data' field

thinc/backends/ops.py
The `list2padded` operation didn't reorder the sequences, so the batches were entirely incorrect.
=> Fix ordering in list2padded op

thinc/layers/staticvectors.py, thinc/model.py
`StaticVectors` didn't work for me, it got the wrong output dimensions. I shuffled the code around, more or less as it used to be. This seems to at least fix the training step.
A review would be good because I'm not entirely confident.
Also, there's still quite a bit to do on the current spaCy `develop` branch with respect to `StaticVectors`, `cfg` passing, IO etc, so I haven't yet been able to test this end-to-end yet, which is why I'm suggesting to have this as WIP (see also https://github.com/svlandeg/spaCy/tree/feature/static-vectors).
=> Fixing StaticVectors

azure-pipelines.yml, thinc/neural/_murmur3.cu
Add fix for GPU/Windows processing from PR https://github.com/explosion/thinc/pull/149, so we can include it in the release of spaCy 2.2.4
=> Fix murmur hash on v7.x

thinc/layers/embed.py, thinc/tests/layers/test_layers_api.py, thinc/tests/layers/test_uniqued.py
Use `nV` rather than `nV + 1` to remove all whiffs of OOV handling from `Embed`.
=> Set Embed shape to (nV, nO)

azure-pipelines.yml
Only install mxnet on non-windows platforms where it has a valid wheel. The project specifies a generic wheel for the `1.6.0` release that fails to install on our Windows CI build.
=> Fix CI build on Windows

.gitignore, thinc/model.py, thinc/tests/layers/test_feed_forward.py, thinc/tests/layers/test_uniqued.py
As we may need to copy/set the `Model`'s `init` function in downstream applications, renaming from `_init` to `init`.
Also expanded / structured the `gitignore` file, similar as how we're doing it in spaCy. Nothing was removed from the original list.
=> init instead of _init

examples/00_intro_to_thinc.ipynb
When running the example notebook *00_intro_to_thinc.ipynb* on a Colab GPU runtime, the section that loads the data from config will fail with the following error:
```
<ipython-input-21-be6cf6a02f24> in <module>()
5 (train_X, train_Y), (dev_X, dev_Y) = loaded_config["training"]["data"]
6 
----> 7 model.initialize(X=train_X[:5], Y=train_Y[:5])
8 train_model(((train_X, train_Y), (dev_X, dev_Y)), model, optimizer, n_iter, batch_size)
ValueError: Encountered a numpy array when processing with cupy. Did you call model.ops.asarray on your data?
```
To solve this issue, we simply need to explicitly assure that the data is on the correct device, as done earlier in the notebook when first building the dataset.
Another way could be to implicitly move the data to the right device when calling …
=> Example Notebook: Make sure data is on the right device after loading from config

azure-pipelines.yml
It looks like Azure is deprecating old 10.13 mac images, so try updating them to 10.15
>This job was temporarily blocked because it uses a Microsoft hosted agent (MacOS-10.13) that will be permanently removed on March 23rd, 2020.  See https://aka.ms/blocked-hosted-agent for more information.
=> chore: update mac os images on azure

thinc/backends/cupy_ops.py
`cupy.scatter_add` has been moved to `cupyx.scatter_add`. It was already deprecated for some time, but now this is actually breaking since cupy-cuda v8.
Fixes https://github.com/explosion/spaCy/pull/5193
=> use cupyx for scatter_add

thinc/layers/staticvectors.py
Also moved some lines. Not sure this actually ever worked correctly before? cf https://github.com/explosion/thinc/blob/v7.x/thinc/neural/_classes/static_vectors.py#L66 - looks like `mask` was always `None` previously?
Anyway this fix does boost spaCy's parser performance by 0.5pp.
=> multiply by drop_mask in staticvectors.backprop

thinc/about.py, thinc/model.py, thinc/tests/test_serialize.py
If we have a mixed model with CPU & GPU layers, the current IO doesn't work because `model.from_bytes` [converts](https://github.com/explosion/thinc/blob/master/thinc/model.py#L507) the read data with `msg = convert_recursive(is_xp_array, self.ops.asarray, msg)` which results in all-cupy or all-numpy arrays across the model.
We used to have layer-specific conversions though, cf. https://github.com/explosion/thinc/blob/v7.x/thinc/neural/_classes/model.py#L357, but this has gotten a bit more tricky with the current design using `convert_recursive`.
This PR has a quick hack that does the conversion of a `param` once more before actually setting it. It feels a little inefficient, because an array may be converted from `numpy` to `cupy` and back... But this keeps the code change minimal. Happy …
=> Fix CPU/GPU IO by checking the layer before setting the param

thinc/backends/__init__.py, thinc/layers/add.py, thinc/model.py, thinc/optimizers.py, thinc/shims/mxnet.py, thinc/shims/pytorch.py, thinc/shims/tensorflow.py, thinc/tests/layers/test_linear.py, thinc/tests/layers/test_sparse_linear.py, thinc/tests/layers/test_uniqued.py
The `Optimizer` object can't assume that all layers are using the same backend, because we might have mixed CPU/GPU execution. So the optimizer needs to fetch an ops appropriate to the inputs.
We remove the `ops` argument to the optimizer, and add a helper `get_array_ops`.
=> Remove ops attribute from Optimizer

azure-pipelines.yml, requirements.txt, thinc/about.py, thinc/layers/add.py, thinc/layers/concatenate.py, thinc/tests/test_examples.py
I think I figured out how we can test our ipython notebooks in the `examples` folder! The `nbconvert` package provides [a way to execute notebooks](https://nbconvert.readthedocs.io/en/latest/execute_api.html#executing-notebooks-using-the-python-api-interface)
When there's an error it looks like this:
The downside to these tests is that they can be slow, or break if you don't have the right system configuration (e.g. no GPU for config notebook). I put the notebooks that execute quickly in one test, and the others in one that is wrapped with `@pytest.mark.slow`
Changes
- run notebooks files in `examples` folder and assert that there are no errors in cell outputs
- add a slow test for the notebooks that take a long time to run
=> Add tests for notebook examples

thinc/shims/mxnet.py, thinc/shims/pytorch.py
Found 2 cases where the renaming of the old `max_grad_norm` to the new `grad_clip` was not done yet.
=> max_grad_norm was renamed to grad_clip

thinc/initializers.py, thinc/model.py, thinc/tests/layers/test_uniqued.py
Includes Lecun_Unfiorm, He_Uniform and Glorot_Normal initializers - Reference - https://keras.io/initializers/ 
Completes - 
TODO: Harmonize naming with Keras, and fill in missing entries https://keras.io/initializers/ We should also have He normal/uniform and probably lecun normal/uniform.
Will add Lecun and He Normal once Glorot normal is approved
=> Support for additional initializers from keras

azure-pipelines.yml, thinc/tests/layers/test_mxnet_wrapper.py, thinc/tests/test_util.py, thinc/util.py
The to_categorical helper outputs different shapes than PyTorch and TensorFlow equivalent helpers. 
This "fixes" it so that Thinc/TF/Torch all agree on the output.
- resume testing to_categorical helper _(lol at xfail reason)_
- to_categorical restores the input shape before returning
- closes #339
=> fix(to_categorical): make consistent with tf/torch one_hot helpers

thinc/shims/pytorch.py
Fixes pretty bad bug: if there were schedules set for learning rate etc, the PyTorch shim wasn't receiving the updated values.
We should update the shims to call into Thinc's optimizer. The current way is pretty brittle :(
=> Update learn rate etc in pytorch shim, if schedule

azure-pipelines.yml, thinc/tests/test_examples.py
This should allow us to test the stable notebook tests while skipping the ones that need graphviz
=> remove graphviz from azure and skip visualizer tests

thinc/shims/mxnet.py, thinc/shims/pytorch.py, thinc/shims/tensorflow.py, thinc/tests/layers/test_pytorch_wrapper.py, thinc/tests/layers/test_tensorflow_wrapper.py
Update the shim classes to use the thinc optimizers instead of creating framework-specific ones.
=> Use thinc optimizer in Shim classes

thinc/about.py, thinc/layers/chain.py
- ensure chained layer only has `nI` if the first layer has one (this was causing failures in spaCy because it would try to run `get_width` on a `Doc` otherwise)
- bump to 8.0.0a8
=> fix nI in chain

thinc/backends/_custom_kernels.py, thinc/backends/ops.py, thinc/model.py, thinc/shims/mxnet.py, thinc/shims/pytorch.py, thinc/shims/shim.py, thinc/shims/tensorflow.py, thinc/tests/layers/test_linear.py, thinc/tests/layers/test_tensorflow_wrapper.py
Most other libraries' optimizers work on a group of parameters at once. This changes the definition of gradient normalization, which causes an annoying mismatch between our hyper-parameter values and e.g. PyTorch. It probably doesn't matter, but it's another thing for people to worry about. Optimizing lots of small arrays also makes our optimizer quite slow.
Instead, we can merge the parameters and gradients together and just call the optimizer once. The question is whether we should do this within the `Optimizer` class. Maybe? For now the merging and flattening is duplicated in the shims...
We do create an extra copy of the parameters when we do this, which is a bit unideal, but I don't really see a way to help it.
=> Optimize parameters in bulk

thinc/backends/numpy_ops.pyx
Leaving it off by default is a big hassle, and caused some bad performance in spaCy that was hard to track down.
=> Enable blis by default

thinc/layers/dropout.py
This was a pretty bad bug! Likely affected some of our spaCy v3 experiments.
=> Only enable dropout in training mode

thinc/config.py
quick fix to help debugging when messing up formatting the config file ... (debugging for a friend)
=> add informative error message when part of the config can't be parsed

examples/03_textcat_basic_neural_bow.ipynb
Updates vocab size and model definition for changes since 8.0.0a1.
Fixes #354.
=> Update textcat example to thinc==8.0.0a9

thinc/about.py, thinc/config.py, thinc/tests/test_config.py
This PR adds support for a dictionary `overrides` that can be provided to `registry.make_from_config` and `registry.fill_config`. This feature allows implementing workflows that need a mechanism to overwrite config settings without editing the config file, e.g. via a CLI (the intended use in spaCy). 
Overrides are applied as the config is resolved and should be passed in as a dictionary, keyed by config properties using the dot notation:
```python
{"section.subsection.value": 123, "other_section.foo": "bar"}
```
Values are substituted before a section is validated, so overwriting a typed argument with a value of the wrong type will raise a regular config validation error. It's also possible to overwrite "promises" (references to registered functions), e.g. to overwrite a schedule with a …
=> Add overrides option to fill_config and train_from_config

thinc/about.py, thinc/config.py, thinc/tests/test_config.py
This catches a common typo case where you have something like:
```
[nlp.pipeline]
blah = true
[nlp.pipline.ner]
@architecture = "tok2vec.v1"
[nlp.pipeline.ner.model]
...
```
These errors are otherwise difficult to catch, as we'll end up complaining about the validation of the `"tok2vec.v1" function as it's missing its arguments...Which look like they're provided, unless the user sees the typo.
So you have to open a block, you can't create nested structures all in one section command. The only exception is the `*` block used for lists, which it wouldn't make sense to create explicitly.
I've made a separate error, `ConfigStructureError` for this as I didn't want the same error args as the `ConfigValidationError`. I did inherit from `ConfigValidationError` though, so people only have to …
=> Raise error if expanding undefined config block

thinc/config.py, thinc/tests/test_config.py
Previously if you had `{"optimizer": {"foo": {"bar": 1}}`, the printed string would not create the `[optimizer]` block as it didn't have any leaf values. That now fails parsing due to the change in #362.
=> Make config.to_str() create intermediate blocks

thinc/layers/concatenate.py
The backprop calls take `List`'s as input, I think there's no need for the `asarray` transformations. They don't matter for `numpy` (I assume because of duck typing), but on GPU `cupy` throws an error because of the varying lengths and a resulting `Unsupported dtype object`.
This fix makes `CharEmbed` / the morphologizer work again on GPU / spaCy (together with https://github.com/explosion/spaCy/pull/5757)
=> fix concatenate (list) on GPU

thinc/about.py, thinc/config.py, thinc/tests/test_config.py
* Fix handling and validation of registered functions returning dicts when config is filled and validated.
* Add `registry.resolve` shorthand that fills and resolves a config (so we don't have to call into `registry._fill` from spaCy etc.)
=> Fix handling of dict return values, add registry.resolve

thinc/about.py, thinc/config.py, thinc/tests/test_config.py
```diff
[section]
+ subsection = {"@some_registry": "SomeFunction.v1"}
- [section.subsection]
- @some_registry = "SomeFunction.v1"
```
=> Config enhancements

thinc/model.py, thinc/tests/model/test_model.py
Writing the conditional logic for the getters is inconvenient, but we don't want to return `None` from those methods, or the type-guarantees will be greatly weakened. Instead I suggest we have separate methods that are allowed to return `None`.
=> Add maybe_get_{dim, param, grad, ref} methods

thinc/config.py, thinc/tests/test_config.py
Resolves #352.
This PR improves how variable interpolation is handled in configs and adds support for referencing blocks. Even the basic interpolation ended up being tricky to support, because we need to make sure that values are loaded with `json.loads` _before_ they're substituted, so you don't end up with `"hello ${value}"` -> `"hello "value""`.
Some examples of what's possible now (also see the tests for more):
```ini
[paths]
root = "/some/path"
some_int = 10
[section]
my_path = "${paths:root}/some/subpath"
my_other_path = "${paths:root}/some/subpath/${paths:some_int}"
```
```ini
[section]
some_value = "value"
[other_section]
some_value = ${section}
```
```ini
[section]
some_value = "value"
[section.subsection]
other_value = 20
[other_section]
some_value = ${section.subsection}
```
* …
=> Support extended config interpolation

thinc/config.py, thinc/tests/test_config.py
The `Config.from_str`, `Config.from_bytes` and `Config.from_disk` methods can now take optional `overrides` that are added to the config parser _before_ the config is interpreted. This allows overwriting values that are referenced as variables in other sections, without breaking the config.
```ini
[section]
a = 2
b = 3
[section.subsection]
c = "hello"
[other_section]
d = ${section:a}
e = ${section.subsection}
```
```python
overrides = {"section.a": 20, "section.subsection.c": "world"}
config = Config.from_str(config_str, overrides=overrides)
```
```python
{
"section": {
"a": 20,
"b": 3,
"subsection": {
"c": "world"
},
"other_section": {
"d": 20,
"e": {
"c": "world"
}
}
}
```
=> Allow config overrides on creation (and used with interpolation)

thinc/config.py, thinc/util.py
Some background on `raise` with `from`: https://stackoverflow.com/a/24752607/6400719
It's probably a good code practice we should adopt in spaCy as well? This will:
* remove the extensive traceback caused by raising and reraising exceptions during config validation (`from None`)
* in custom exceptions based on other relevant exceptions (like, if copying the config fails because of an error in `deepcopy`): raising it from the original error means the traceback will read: "The above exception was the direct cause of the following exception:"
=> Use "raise ... from" in custom errors for better tracebacks

thinc/about.py, thinc/config.py, thinc/tests/test_config.py
* Allow setting `interpolate=False` on `Config.to_str`, `Config.from_str` and other serialization methods. This will preserve variables in the configs, and will make it easier for us to provide "starter configs" that can be filled without destroying the variables.
* Support non-interpolated configs in `registry.resolve`: in that case, we keep a copy of the original config, fill and resolve the interpolated version (because that's the only way it can work) and then merge the original config with its variable references back into the filled config. This makes it possible to auto-fill a config with variables and add missing defaults etc. while keeping the references intact.
* Add `Config.interpolate` method to interpolate an existing config (returns a copy).
* Port config merging logic over …
=> Support optional variable interpolation and fix config resolution

thinc/about.py, thinc/config.py, thinc/tests/test_config.py
This is relevant, because it impacts how a config is resolved and whether it's interpolated before.
```python
config_str = """
[variables]
width = 123
[model]
@architectures = "my_model"
width = ${variables:width}
"""
@registry.architectures("my_model")
def my_model(width: int, depth: int = 456):
...
```
Auto-fill partial config (e.g. as part of `init config` command)
```python
config = Config().from_str(config_str)
filled = registry.fill_config(config)
```
Result:
```ini
[variables]
width = 123
[model]
@architectures = "my_model"
width = 123
depth = 456
```
Problem: reference to `${variables:width}` is gone. A user's CLI script that overwrites `--variables.width` will now produce different and very misleading results. All the convenience of referencing blocks and values is gone, just …
=> Fix reporting of whether config is interpolated

thinc/about.py, thinc/config.py, thinc/tests/test_config.py
Allows passing in a `sort_key`, a function that takes `(key, value)` tuples. Only applied to the top-level sections. The default alphabetic order isn't always the best.
=> Support custom sort in serialization methods

thinc/about.py, thinc/config.py, thinc/tests/test_config.py
Configs support variables of two different types: references to other values via `${a:b}` (like Python's regular configparser) and references to other sections via `${a.b}` (requires a custom implementation where we add a placeholder and then substitute the block once the config is interpreted).
* It's very easy to make mistakes here and accidentally write `${a.b}` instead of `${a:b}`.
* The value vs. section distinction makes sense on the implementation level, but not actually from the usage perspective: values in a Thinc config can be set explicitly or using a section (`batch_size = 128` vs. `[training.batch_size]`). There's virtually no difference in terms of the result it produces, and a user can easily swap in a section and vice versa. So having to change a variable reference from …
=> Support ${a.b} and ${a:b} in variables for values and sections

thinc/about.py, thinc/config.py, thinc/tests/test_config.py
When filling and resolving a config, there are currently two options:
* with validation: will raise an error if values are wrong or missing
* without validation: will fill in all gaps and try to fix problems but not raise errors
However, we didn't handle extra values if validation was disabled. In that case, we're only constructing the config from the schema (in the most efficient way possible, using `pydantic`). So we need to filter all fields that are not in the original schema manually, if the schema says it doesn't allow extra fields.
To make this work consistently with both interpolated and non-interpolated configs, we need a little hack: to restore the variabels, we're merging the original non-interpolated config into the final filled config. This works fine, unless the original …
=> Support remove extra fields from config when filling

thinc/about.py, thinc/layers/with_cpu.py, thinc/shims/pytorch.py
I couldn't get the `textcat` shape inference to work properly in spaCy. Ultimately tracked it down to `with_cpu` that was not properly hooked up with the right dimensions. This should fix it.
Also changed the name to include the encapsulated layer, as that simplifies debugging.
Bump to 8.0.0a31
=> fix with_cpu shape inference

thinc/layers/residual.py, thinc/layers/uniqued.py, thinc/layers/with_array.py, thinc/layers/with_debug.py, thinc/layers/with_flatten.py, thinc/layers/with_getitem.py, thinc/layers/with_list.py, thinc/layers/with_padded.py, thinc/layers/with_ragged.py, thinc/layers/with_reshape.py, thinc/tests/layers/test_lstm.py
Maybe it's just me, but I kind of like analyzing a layer/model's architecture using its name. The "syntax" using `-` gets unusable with many nested layers though, so proposing `()` here instead.
=> nested names

thinc/about.py, thinc/config.py, thinc/tests/test_config.py
There was an issue when merging a config with a default. If the original config has a promise (`@foo`) but the default has something else that doesn't match, the default values would still get added in the merged version. This was because the `continue` in the code started from the viewpoint of the default config. So I think we need both viewpoints - hence the second condition for another `continue`.
Hopefully the new unit tests make it clear. We need this behaviour to be able to implement different version of `training.corpus` in spaCy.
=> check for conflicting promise before merging

thinc/about.py, thinc/config.py, thinc/tests/test_config.py
This makes it easier to test for specific config validation errors (because we can easily inspect the errors in a structured way) and re-raise modified versions of the error (e.g. in spaCy).
=> Refactor ConfigValidationError and make it more extensible

examples/00_intro_to_thinc.ipynb, examples/02_transformers_tagger_bert.ipynb, examples/03_pos_tagger_basic_cnn.ipynb, examples/03_textcat_basic_neural_bow.ipynb, examples/04_parallel_training_ray.ipynb, examples/benchmarks/lstm_tagger.py, examples/transformers_tagger.py, thinc/about.py, thinc/config.py, thinc/tests/layers/test_layers_api.py, thinc/tests/layers/test_transforms.py, thinc/tests/test_config.py, thinc/tests/test_initializers.py, thinc/tests/test_loss.py, thinc/tests/test_optimizers.py, website/docs/api-config.md, website/docs/api-initializers.md, website/docs/api-loss.md, website/docs/usage-config.md, website/docs/usage-training.md
- Allow configs to be filled without resolving. In this case, registered functions (promises) aren't called or even loaded and their return values aren't validated against any schema.
- Only use two descriptive methods: `registry.fill` returns a filled, unresolved config and `registry.resolve` returns the resolved config
=> Refactor filling and resolving config

thinc/about.py, thinc/config.py, thinc/tests/test_config.py
If we're just filling a config, promises that refer to registered functions that are not available should be ignored.
=> Handle promises with unavailable references if resolve=False

thinc/model.py, thinc/tests/test_serialize.py, website/docs/api-model.md
This should allow us to look before we leap to avoid confusing errors. I've called the methods `model.can_from_disk(path)`, `model.can_from_bytes(bytes_data)` and `model.can_from_dict(msg)`. By default, if the model is initialized and the data would cause us to change an attribute value that's already been set, we return `False`, even though that would be legal. This can be changed by setting `strict=False`.
=> Add Model methods to check deserialization compatibility

requirements.txt, setup.cfg
Need to have `pydantic>=1.5` to use `field.default_factory`
cf https://pydantic-docs.helpmanual.io/changelog/#v15-2020-04-18
=> upgrade pydantic pin to use field.default_factory

thinc/about.py, thinc/api.py, thinc/backends/numpy_ops.pyx, thinc/config.py, thinc/util.py, website/docs/api-util.md
Add convenience method `require_cpu` that makes sure to use `NumpyOps`.
Implemented after reading the discussion here: https://github.com/explosion/spaCy/issues/5018
=> require_cpu

thinc/extra/search.pyx
Rename `Beam.__del__` to `Beam.__dealloc__`.
=> Fix finalization method name for Beam

pyproject.toml
* Remove detailed numpy build constraints from `pyproject.toml` because
it is too difficult to maintain for many architectures
* These constraints are more a reflection of what is available on
pypi as binary wheels rather than any real build requirements that
it is necessary for users to follow when building from source
* Users building their own binary packages will need to enforce the
constraints that make sense in their environments, e.g., the `conda`
compatible numpy pins
* Keep the build constraints in `build-constraints.txt` for use with our
builds
* Our builds with wheelwright are built against the earliest
compatible binary versions of numpy on pypi
* These constraints are documented within the distribution
=> Remove detailed numpy build constraints

thinc/layers/parametricattention.py, thinc/layers/residual.py
Only initialize the internal layer of `residual` with `Y` if the output dim `nO` is yet to be determined.
This is necessary to avoid wrong shape inferences stemming from the `chain` layer. This is all a bit brittle, and perhaps we want to rethink the whole shape inference mechanism at some point, but for now I think this works.
=> avoid initializing with Y if not necessary

thinc/model.py, website/docs/api-model.md
The documentation of the `Model` constructor seems to have gone out of date: `grads` is not a parameter anymore, but `refs` is.
Also removed some dead code from `Model.copy`
=> update Model documentation

thinc/layers/lstm.py, thinc/layers/pytorchwrapper.py, thinc/layers/with_array.py, thinc/layers/with_cpu.py, thinc/layers/with_list.py, thinc/layers/with_padded.py
spaCy issue https://github.com/explosion/spaCy/issues/6318 pointed towards some issues with inferring dimensions. To better support chaining layers and shape inference, this PR:
- transfers dimensions from the encapsulated layer in the `with_X` type-transformation layers
- sets an appropriate `nO` and `nI` dimension on the `PyTorchLSTM`
=> Propagate dims

README.md, azure-pipelines.yml, setup.cfg, website/docs/install.md
* Remove upper torch pin in extras, users are on their own to uninstall `dataclasses`
* Switch to `+cpu` in CI tests for smaller downloads
=> Update torch pins

requirements.txt, setup.cfg, thinc/tests/test_config.py, thinc/types.py
Don't use private dataclass fields for now (which conflict with the way Pydantic validates dataclasses in > 1.7).  This should make Thinc and by extension spaCy work with the latest Pydantic and Python 3.9.
=> Make dataclasses work with Pydantic >= 1.7

thinc/backends/_custom_kernels.py
Running pytest on my project results with the following error:
```shell
/usr/local/lib64/python3.8/site-packages/thinc/neural/_custom_kernels.py:36                                                                                                                                      
/usr/local/lib64/python3.8/site-packages/thinc/neural/_custom_kernels.py:36: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/lib64/python3.8/site-packages/thinc/neural/_custom_kernels.cu' mo
de='r' encoding='utf8'>                                                                                                                                                                                            
SRC = (PWD / "_custom_kernels.cu").open("r", encoding="utf8").read() 
```
This happens because …
=> fix ResourceWarning for opening a file without explicitly closing it

thinc/api.py, thinc/layers/__init__.py, thinc/layers/concatenate.py, thinc/layers/reduce_first.py, thinc/layers/reduce_last.py, thinc/tests/layers/test_reduce_first_last.py, thinc/util.py
I've wanted these for a while. They're especially useful after LSTM and transformer models, where it makes sense to interpret the first or last vector as the representation of the whole sequence.
=> Add reduce_first and reduce_last layers

thinc/api.py, thinc/layers/__init__.py, thinc/layers/with_array.py, thinc/layers/with_array2d.py, thinc/tests/layers/test_with_transforms.py
When working on more examples, I've found I often need the `with_array` layer to behave differently than how we had it. I wanted it to not reshape the data, so that I can easily get at the `Array3d` that's behind a `Padded` layer. But other times you do want to get the concatenated sequence representation back out.
My answer is to have two layers, `with_array` and `with_array2d`. I think it's better to have a different wrapper than to have an argument, because with an argument the type signatures get out of control.
=> Separate with_array and with_array2d layers

thinc/tests/model/test_validation.py, thinc/util.py
This PR disables the default type validation that would happen on `model.initialize()`, as it causes runtime errors if types are wrong. Specifying types entirely correctly can be fiddly, so raising runtime errors from the types can lead to problems.
A particular problem at the moment is that the `chain()` combinator cheats and passes in the Y output into non-final layers to assist with shape inference. This means that layers which define a type on that Y variable during init can fail validation. While the current state is a hack, more generally I think it's a bad idea to have a default that raises a runtime error on the types. The type errors also are not necessarily easier to debug than the runtime error.
=> Disable default input/output validation on initialize

thinc/api.py, thinc/backends/ops.py, thinc/layers/__init__.py, thinc/layers/hashembed.py, thinc/layers/logistic.py, thinc/layers/sigmoid.py, thinc/layers/sigmoid_activation.py, thinc/tests/layers/test_layers_api.py
The current `Logistic` layer has a name that's inconsistent with the rest of the layers. You'd expect based on its name that it has a dense weight layer, like `Softmax` and `Relu` do. Instead `Logistic` is activation-only.
Changing the behaviour of the layer will be too breaking, and the name isn't great anyway. We should just follow Keras and call this the "sigmoid" activation (like it actually is in the `Ops` class anyway!).
I've added two layers: `sigmoid_activation()` does what `Logistic` currently does, and `Sigmoid` provides a linear layer in addition to the activation.
=> Deprecate name 'Logistic' in favour of Sigmoid and sigmoid_activation layers

thinc/backends/ops.py, thinc/tests/layers/test_with_transforms.py, thinc/types.py
The list2padded op was doing the "get indexes by length" step twice, which left the sequences unsorted by length. This messes up a bunch of logic, meaning that layers wrapped with `with_padded` wouldn't converge (oops).
The fix comes with a better test for these transforms, to check that they don't disrupt the values when wrapping a noop layer.
=> Fix list2padded op

azure-pipelines.yml, requirements.txt, thinc/config.py, thinc/model.py, thinc/shims/shim.py, thinc/tests/backends/test_ops.py, thinc/tests/conftest.py, thinc/tests/layers/test_shim.py, thinc/tests/model/test_model.py, thinc/tests/test_config.py, thinc/tests/test_util.py
With spaCy 3, saving models to Pathy paths has stopped working. 
It turns out that thinc is forcing the input paths to be a Path class by wrapping them "just to be sure". It's friendly and concise, but it messes with inputs that are already path-like objects.
I added tests to demonstrate the failure, and as a fix, I only coerce the type to Path if it is a string.
Related to: https://github.com/justindujardin/pathy/pull/44
=> fix(pathy): don't force input paths to Path when de/serializing objects

thinc/layers/layernorm.py
Inspired by [this issue](https://github.com/explosion/spaCy/issues/6946). The "trouble" is being caused by the shape inference code in `chain`, but it can't hurt to add some additional robustness into `layernorm` to avoid using `Y` if not necessary.
=> avoid initializing with Y if X is set

azure-pipelines.yml
Seems to currently cause segfaults for python 3.9 in linux in the CI, although no idea what the underlying cause might be.
=> Disable code cov in CI

requirements.txt, setup.cfg
sync pins with spacy - cf https://github.com/explosion/spaCy/pull/7247
Triggered by the fact that `ml_datasets` still referred to a specific alpha version.
=> sync pins with spacy

thinc/api.py, thinc/layers/__init__.py, thinc/layers/map_list.py, thinc/tests/layers/test_combinators.py, website/docs/api-layers.md
Add a combinator layer that maps a child layer across list inputs. I happened to need this to show how to do something for spaCy, and I thought I'd added this already but it wasn't there.
I think in Thinc v7 there was a similar layer called `foreach`. A name with `map` seems better, and apparently in list it's called `maplist`. I hate arbitrary non-underscore names, hence `map_list`.
=> Add map_list layer

thinc/layers/lstm.py, thinc/tests/layers/test_layers_api.py
Fixes https://github.com/explosion/spaCy/issues/7088
When using a biLSTM, the given `nO` dimension of the Thinc model would be divided by half and stored as such. I think this behaviour is unexpected, and it clashes with some of the shape inference & listener code in spaCy.
I think it makes more sense to keep the given `nO`, but provide the Torch model with half the value for its hidden features, so that the final output matches the required `nO` dimension.
This PR changes the behaviour both for `PyTorchLSTM` and `LSTM` (if `bi` is `True`) - both would otherwise predict vectors that were incompatible with their internal `nO` value - cf test and spaCy issue linked above.
The additional line in the test makes `CauchySimilarity` error as well. Not sure (yet) whether this is due to an error …
=> ensure consistency of nO dim for biLSTM

thinc/about.py, thinc/config.py, thinc/tests/test_config.py
Before this PR, the `config.from_str` method would interpolate before setting the overrides. This meant that a string such as `"hello ${vars.a}"` would get interpolated first - i.e. changing `vars.a` with the value from the config, and only afterwards would this value be changed again into the correct one from `overrides`.
This mechanism resulted in unnecessary quotes when strings were being inserted into other strings, as examplified by the unit tests. Before this PR, most of the `test_config_overrides` configurations would fail (especially the ones more down the bottom).
Instead, this PR ensures that interpolation only happens after setting the overrides, circumventing the quoting behaviour.
While that fixes most of the tests, one additional issue couldn't be resolved: if you have an …
=> Fix config override & interpolate interaction

azure-pipelines.yml
It turns out that the recently released `pip` 21.1 makes our CI fail on Windows. The `pip uninstall` command runs into permission issues with `shutil`, stopping the CI early. 
Pinning `pip` to 21.0 on the CI, as in this PR, resolves the failures, but this solution is obviously not great for longer term. Still, we might consider patching this for now so we can get on with Thinc PRs.
=> CI failing with pip 21.1

requirements.txt, setup.cfg, thinc/util.py
Hi there! :wave:
Let me start with: I don't know exactly how this start failing. :sweat_smile: 
Maybe you'll understand better looking at the explanation: https://github.com/samuelcolvin/pydantic/issues/2678#issuecomment-821437650
The solution I proposed is the one presented in the link above. An alternative could be: 
```python
ArgModel.update_forward_refs(**globals())
```
(but you'll get more than you need... and I'm not sure it works in all cases)
=> 🐛 Add update_forward_refs with local models

requirements.txt, setup.cfg
Increase upper pin to `<1.9.0`. Forbid versions with security vulnerability:
https://github.com/samuelcolvin/pydantic/security/advisories/GHSA-5jqp-qgf6-3pvh
=> Update pydantic requirement

thinc/tests/layers/test_basic_tagger.py, thinc/tests/layers/test_mnist.py, thinc/tests/model/test_model.py, thinc/tests/mypy/test_mypy.py, thinc/tests/test_examples.py
Skip mypy, ml_datasets and notebook tests if those (dev-only) requirements are missing. (Primarily due to problems running the test suite on conda-forge.)
=> Skip tests if packages are missing

thinc/api.py, thinc/layers/__init__.py, thinc/layers/tuplify.py, thinc/tests/layers/test_combinators.py, website/docs/api-layers.md
Tuplify replicates the input so that it can be modified separately by
downstream layers.
This needs tests and probably other metadata settings added still.
=> Add tuplify

thinc/layers/concatenate.py
Originally opened to address https://github.com/explosion/spaCy/pull/8012
That was solved within `spacy`. This PR now only involves a more general implementation of the current functionality.
=> Avoid concatting `None` gradient

requirements.txt, setup.cfg
Require `catalogue>=2.0.4` due to bugs in v2.0.3 related to `importlib-metadata`.
=> Require catalogue>=2.0.4

thinc/initializers.py
Update initializers to cast values to the thinc-specific types supported by the ops.
=> Update initializers for typing in numpy 1.21+

thinc/loss.py, thinc/tests/test_loss.py
`SequenceCategoricalCrossentropy` can be called with a `truths` array consisting of strings. This PR allows a `neg_prefix` to be defined that signals to the loss function that a given string is negated - i.e. it is a negative annotation.
This way, calculation of the loss can directly take into account a negated value.
This will allow us to train the tagger on labels such as `"!NN"`, without changing much on the spaCy side. The only requirement will be to define the `neg_prefix`. I'll be adding a unit test to spaCy that nicely illustrates this.
- input: `truths` array, e.g. `[['!N', 'V', 'J', 'N']]`
- ignoring the negative prefix `!`, this will be converted to indices according to the known labels: `[1, 2, 0, 1]`
- this PR additionally keeps track of a `negatives_mask` which is `1` for all …
=> allow negated values in CategoricalCrossentropy

thinc/backends/numpy_ops.pyx, thinc/tests/backends/test_ops.py
I am reading various parts of the thinc source code to see how things work, I found a small inconsistency in the numpy `gemm` op:
The `out` keyword argument of the `gemm` op specifies an output array. However, the semantics were different depending on whether BLIS is used:
* `use_blis==False`: the values of out array are overwritten.
* `use_blis==True`: the values of out are added to the result.
With this change, the values of `out` are also overwritten with `use_blis=True`.
=> Fix numpy_ops gemm output semantics when BLIS is used

requirements.txt
I have only increased the upper ranges. Some combination of older versions and newer dependencies (`nbclient`?) is incompatible, but I'm not sure exactly what.
=> Use newer releases of nbconvert and nbformat

requirements.txt, thinc/mypy.py, thinc/tests/regression/issue519/program.py, thinc/tests/regression/issue519/test_issue519.py
These changes fix a crash that would occur in the Thinc Mypy plugin whenever a Thinc API function was called with variadic arguments.
Previously the Thinc Mypy plugin would treat any argument with a generic type as a `Model` instance and attempt to infer a more specific type for the return type of the function call. However, the Thinc Mypy plugin was intended to only be used on functions that exclusively accept and return `Model` instances. Since the plugin accepted overly broad input, it would sometimes end up trying to access the second generic type argument for a generic type instance with only a single argument. This resulted in the plugin crashing.
This specifically manifested itself whenever variadic arguments were passed to a Thinc API function. Mypy passes the type of variadic …
=> 🐛 Fix Mypy plugin crash on variadic arguments

thinc/api.py, thinc/layers/__init__.py, thinc/layers/with_nvtx_range.py, thinc/util.py, website/docs/api-layers.md
This PR adds the following:
* the `with_nvtx_range` layer that wraps any layer and marks the `forward` and `backprop` passes as an NVTX range. This can be helpful when profiling GPU performance of one or more layers.
* the `use_nvtx_range` context manager, which can be used to mark a scope as an NVTX range.
The ranges are used to mark executions in nvprof or NSight profiles and make it easier to see to which layers/code CUDA operations are associated.
=> Add context manager and layer wrapper for marking NVTX ranges

thinc/api.py, thinc/model.py, thinc/tests/model/test_model.py
This is a simple wrapper function that recursively wraps a Model and its layers recursively.
Useful for e.g. recursively wrapping forward/backprop passes in NVTX ranges.
=> Add wrap_model_recursive

thinc/api.py, thinc/layers/pytorchwrapper.py, thinc/shims/__init__.py, thinc/shims/pytorch.py, thinc/shims/pytorch_grad_scaler.py, thinc/tests/shims/pytorch_grad_scaler.py, thinc/util.py
This change adds support for mixed-precision training and prediction to
the PyTorch shim. Mixed-precision support consists of two parts:
- Autocasting of the forward pass. This changes whitelisted ops to run
in half precision rather than single precision.
- Gradient scaling. Gradients underflow quickly in half-precision.
Gradient scaling increases the magnitude of the gradients during
backprop to avoid underflow.
A separate class, PyTorchGradScaler is introduced to perform gradient
scaling and store the associated state.
---
I hope that I correctly implemented multi-GPU training, but I couldn't test it with my current single GPU workstation.
=> PyTorchShim: add support for mixed-precision

thinc/about.py, thinc/config.py, thinc/tests/test_config.py
Still need to test this against spaCy to check if we need to adjust any tests here. Also a bit worried about potential unitended side-effects (or some important reason why we included this feature that I forgot).
Related: https://github.com/explosion/spacy-transformers/pull/283#issuecomment-903513318
---
The config system currently only allows passing on overrides for existing settings, not new keys. For instance, given a config like this:
```ini
[section]
foo = 1
bar = 2
```
Passing in the overrides `{"section.foo": 3}` is valid, whereas `{"section.baz": 3}` would raise an error. In a lot of scenarios, this makes sense, because you'd expect the config to be complete and describing all available settings – so anything unexpected is likely a problem. But there are other cases where the …
=> Allow config overrides to add new keys

thinc/backends/__init__.py
`get_array_ops` should default to `NumpyOps` rather than the current ops so that numpy arrays are handled correctly.
=> Fix default ops for get_array_ops

thinc/layers/with_debug.py, thinc/layers/with_nvtx_range.py, thinc/model.py, thinc/tests/model/test_model.py
This PR combines two changes:
1. In `wrap_model_recursive`, also make sure that node references are pointing to the wrapped nodes.
2. Pass through dims, refs, attrs, and ops, so that these can be queried when a layer is wrapped.
=> Improve wrapping in with_{debug,nvtx_range}

thinc/loss.py, thinc/tests/test_loss.py
`CategoricalCrossEntropy` provides a `missing_value` option that can be used
to mask instances that have a special label. However, this functionality
only works with non-integer categorical labels.
This change adds support for masking missing values for int lists and xp
arrays.
=> CategoricalCrossEntropy: support missing values for int arrays

thinc/model.py, thinc/tests/model/test_model.py
`Model.replace_node` failed if a node *n* contained a reference to another node *m*, when *m* only occurs in one of the (grand)children of *n*.  Since `replace_node` used the breadth-first `Model.walk` method, the reference to *m* would be replaced before *m* is replaced in the (grand)children of *n*. However, this fails because `set_ref` verifies that the a new node reference occurs in the graph.
This change resolves this issue by replacing nodes using a depth-first search.
=> Fix replace_node on nodes with indirect node refs

azure-pipelines.yml, thinc/__init__.py, thinc/backends/__init__.py
It's currently not possible to import `thinc_apple_ops` because of a circular import related to a change from #540.
This works:
```python
import thinc
import thinc_apple_ops
```
This does not:
```python
import thinc_apple_ops
```
=> Fix circular import related to ops registry

thinc/api.py, thinc/layers/__init__.py, thinc/shims/pytorch.py, thinc/shims/pytorch_grad_scaler.py, thinc/tests/layers/test_pytorch_wrapper.py, thinc/tests/shims/test_pytorch_grad_scaler.py, thinc/util.py
With mixed-precision enabled in a PyTorchWrapper, an update is skipped and the gradient scale is adjusted when one or more of the gradients is Inf/NaN. However, Inf/NaN gradients were still backpropagated into preceding Thinc layers.
This change fixes this issue by clearing gradients of inputs to PyTorchWrapper if Inf/NaN occurs in any of the gradients.
Also:
* Change `PyTorchGradScaler.scale` to accept `Tensor` besides `Sequence[Tensor]`.
* Expose `PyTorchWrapper_v2` in the API
* Add a unit test for mixed-precision training.
---
~Set to draft because:~
=> mixed-precision: do not backprop Inf/NaN out of PyTorch layers

thinc/tests/backends/test_ops.py
Otherwise the test fails with PyToch from the main branch.
=> Set atol for Swish to 1e-6 when comparing output to PyTorch

thinc/backends/_custom_kernels.cu, thinc/backends/_custom_kernels.py, thinc/backends/cupy_ops.py, thinc/backends/numpy_ops.pxd, thinc/backends/numpy_ops.pyx, thinc/backends/ops.py, thinc/tests/backends/test_ops.py
This change adds a `lens` option to `seq2col` and `seq2col_backprop`. When this option is set, the data is divided in sequences with the given lengths. Padding is added for parts of the window that are outside a sequence.
Checks
- The accuracies for existing models does not change:
- The accuracy for a newly-trained model does not change:
- There are no performance regressions for predictions with `lengths=None`:
- There are no performance regressions for training with `lengths=None`:
=> Add support for sequence lengths to seq2col

thinc/tests/shims/test_pytorch_grad_scaler.py
By default the hypothesis deadline is 200ms. The test_scale_random_inputs test would frequently fail because on the first run the deadline was exceeded because GPU initialization takes some time.
=> Remove deadline of test_scale_random_inputs

thinc/backends/_custom_kernels.cu, thinc/tests/backends/test_ops.py
I was profiling the parser refactor and noticed that the maxout kernel is taking more time than I expected:
The maximum amount of parallelism by the kernel is determined by its batch size. However, this leaves the GPU underused. E.g. by default our amount of parallelism is nr_blocks: 128 * nr_threads_per_block: 128 = 16384, which is much larger than the typical batch size.
This PR changes the maxout kernel to parallelize at the output level (each thread computes one output). This makes the maxout kernel about 4.7 times faster with a batch size of 1024 on a RTX 2060 Super:
I haven't updated the backprop variant yet, since it barely appears in the profiles.
=> Speed up maxout by exploiting parallelism better

thinc/api.py, thinc/layers/__init__.py, thinc/layers/softmax.py, thinc/tests/layers/test_layers_api.py, thinc/tests/layers/test_softmax.py, website/docs/api-layers.md
When this option is disabled, unnormalized probabilities (logits) are
returned during inference.
I was not too sure if adding a keyword argument requires making a
new version of the layer. The default behavior is unchanged.
Using unnormalized probabilities during inference can give nice
speedups. E.g. on my M1 Pro, a German tagging/parsing pipeline is
~27% faster with unnormalized probabilities due to not having to
use the expensive `expf` function.
=> Add the `normalize` option to the Softmax layer

thinc/layers/expand_window.py, thinc/tests/layers/test_layers_api.py
Used type variables, so that the caller can be sure that when
they put in a type, they get it out as well.﻿
=> Add support for Ragged to expand_window.v1

thinc/backends/_custom_kernels.cu, thinc/backends/_custom_kernels.py, thinc/backends/cupy_ops.py, thinc/backends/numpy_ops.pyx, thinc/backends/ops.py, thinc/tests/backends/test_ops.py
Improve mish and backprop_mish
* Fix incorrect casting of threshold in CUDA kernels.
* Fix incorrect numerator of backprop_mish in Ops.
* Make mish and mish_backprop invariant to the shape dimensionality.
* Use `inplace` rather than `out` in Ops to work towards a more
uniform API and make it possible to test the Mish activations
against PyTorch.
Also add `mish`/`backprop_mish` to the PyTorch comparison test.
=> Improve mish activation, test against PyTorch

thinc/util.py
This change does not make this function observably faster (even though we are keeping everything on the same device), but I think it is easier to understand:
- We make the one-hot encodings for all classes.
- We select from these encodings based on the class indices.
=> Simplify to_categorical

thinc/config.py, thinc/tests/test_config.py
In a configuration such as the following:
```
[model]
[model.chain]
@layers = "chain.v1"
[model.chain.*.hashembed]
@layers = "HashEmbed.v1"
nO = 8
nV = 8
[model.chain.*.expand_window]
@layers = "expand_window.v1"
window_size = 1
```
The positional arguments in the chain were sorted, changing the chain order. This change masks the names of positional arguments. Since `sorted` is a stable sort, the order of positional arguments is retained.
=> Config: do not sort positional arguments

thinc/backends/cupy_ops.py, thinc/backends/ops.py, thinc/model.py, thinc/tests/backends/test_ops.py, website/docs/api-backends.md
* Add `byte_order` kwarg to `Ops.to_numpy` and `CupyOps.to_numpy`
=> Always serialize Model numpy data with little endian byte order

thinc/tests/backends/test_ops.py
This avoids that the test fails with CupyOps.
=> test_softmax_temperature: use assert_allclose from ops

thinc/backends/ops.py, thinc/tests/backends/test_ops.py
Suppose that we have a sequence of length 2 and dimensionality 3:
```
1: a b c
2: d e f
```
The `which` array specifies for each dimension which sequence contained
the maximum value. For example, if `which = [0, 1, 0]`, the maximum values
were:
```
a e c
```
However, the `Ops` implementation of this function was using which to
select columns. So,
```
a b a
d e d
```
would be selected. This change rectifies this, to select per column the
row indicated in `which`.
=> Fix Ops.backprop_reduce_max

requirements.txt
=> Limit pytest >=5.2.0,<7.1.0

thinc/shims/pytorch.py, thinc/shims/pytorch_grad_scaler.py, thinc/tests/layers/test_pytorch_wrapper.py, thinc/tests/shims/test_pytorch_grad_scaler.py
1. Before this change, using gradient scaling on a non-CUDA tensor would trigger an assertion. However, it is possible to trigger this error outside Thinc by enabling mixed-precision training on a CPU. So this should be a proper exception rather than an `AssertionError`. Besides raising a `ValueError`, the error message is also extended to describe how the error can be avoided.
2.  We checked that gradient scaling is supported when construction a PyTorchGradScaler. However, this gives issues when someone uses a model that was trained with gradient scaling. In such cases, it's safe to contruct a grad scaler, since it is not used. This change moves the check to the actual scaling.
3. Also remove the check that verifies that mixed-precision scaling is available (when enabled) from the …
=> Mixed-precision training: improve checks

thinc/backends/numpy_ops.pxd, thinc/backends/numpy_ops.pyx, thinc/backends/ops.py, thinc/tests/backends/test_ops.py
This PR adds various bounds checks to `NumpyOps` to prevent out-of-bound reads and writes:
- Check that `which` indices are in bounds for `backprop_{maxout, reduce_max}`.
- Check that `dY` and `X` shapes match in backprop for elementwise functions.
- Hook up ReLU to the PyTorch comparison tests.
- Check that lengths are valid in `backprop_reduce_{mean, max, sum}`.
=> NumpyOps: add bound checks

azure-pipelines.yml
`windows-latest` recently [switched](https://github.com/actions/virtual-environments/issues/4856) to `windows-2022`, which doesn't support (end-of-life) Python 3.6 anymore. It doesn't hurt to keep testing this Python version on the CI when we still can, though, so editing this Azure step to use `windows-2019` explicitely.
=> test end-of-life Python 3.6 on windows-2019 image

thinc/backends/ops.py
...to avoid many small GPU <-> CPU transfers.
I still have to benchmark this change to see if this leads to a meaningful training time difference.
=> Do not use an explicit loop in unflatten

MANIFEST.in, setup.py, thinc/backends/cpu_kernels.hh, thinc/backends/numpy_ops.pxd, thinc/backends/numpy_ops.pyx, thinc/tests/backends/test_ops.py
This PR makes most CPU kernels generic, so that they can take both `float32` and `float64` arrays (and hopefully in the future `float16`). I experimented with kernels in Cython + fused types and kernels as C++ with templates, I found the C++ template route more promising:
- More compact/ergonomic implementations with fewer compile-time conditionals.
- Opens up the possibility to easily use SIMD intrinsics in the future.
To allow genericity in the `NumpyOps` method arguments, we use:
- Fused types when we require a specific dimensionality;
- `np.ndarray` otherwise.
Some of the kernels are not (yet) made generic:
- `cpu_scatter_add`: needs tests to verify that the op still works
correctly.
- `cpu_position_encode`: the position_encode op doesn't take float
array(s).
- lstm kernels: I need to …
=> Make NumpyOps CPU kernels generic

thinc/backends/_custom_kernels.py, thinc/backends/numpy_ops.pyx, thinc/backends/ops.py, website/docs/api-backends.md
I've added a new keyword arg `uninitialized` to the allocator methods in the `NumpyOps` and `Ops` classes. Also replaced some zero-init'd allocations where the elements in the destination array were immediately replaced.
=> Reduce unnecessary zero-init'd allocations

thinc/backends/numpy_ops.pyx, thinc/tests/backends/test_ops.py
This change broke `spancat` tests in the spaCy test suite.
=> Revert uninit'd allocs in `Numpy.reduce_max` introduced in #632. 

thinc/backends/cupy_ops.py, thinc/tests/regression/test_issue564.py
This PR fixes the following and adds a regression test:
- The original invocation of `cupy.cuda.MemoryPointer` was missing the mandatory `offset` argument. This should be `0`.
- `cupy.cuda.MemoryPointer` expects a wrapper to a `cupy`-owned CUDA memory and not a raw pointer to it. So, CUDA memory allocated by external libraries needs to be wrapped with `UnownedMemory` and then passed to the array c'tor [[1](https://github.com/cupy/cupy/issues/4644#issuecomment-775480279)].
- We weren't testing that the incoming array-like obj was owned by a CUDA device.
- We were incorrectly passing the array stride as its shape.
Should fix #564.
=> Fix PyTorch tensor handling in `CupyOps.asarray`

thinc/extra/search.pyx
If none of the states of the beam have valid moves, it was attempted to  index into the vector of scored valid moves anyway, which results in invalid memory access.
Fix this by first checking that there valid moves before attempting to  index into them.
@honnibal: I am not sure if this is the valid way to address this issue, but this is the source of access violations on Windows in https://github.com/explosion/spaCy/pull/10633.
=> search.Beam: Fix invalid indexing

thinc/backends/ops.py
Changes from PR #648 rebased onto `explosion:master`.
=> Clamp inputs in `Ops.sigmoid` to prevent overflow

thinc/model.py
It was observed that the test checking typesafe assignment of model IDs failed very occasionally. The issue fixed here is likely to have been the cause of this, although unfortunately there is no way of verifying this.
=> Fix type safety issue with model ID assignment

thinc/backends/_custom_kernels.py, thinc/backends/cpu_kernels.hh, thinc/backends/numpy_ops.pyx, thinc/backends/ops.py, thinc/tests/backends/test_ops.py, website/docs/api-backends.md, website/docs/api-layers.md
* A bug was introduced in `NumpyOps` that caused the output pointer not to be incremented for zero-length sequences.
* When using uninitialized arrays, the sum or mean for a zero-length array was not correctly set to zero in `Ops`.
We should also do something about zero-length sequences for `reduce_max`. However, it's unclear what the corresponding `which` should be set to (since `0` is not a valid index for a zero-sized sequence). Maybe we should throw an exception when trying to apply `reduce_max` to a zero-length sequence?
=> Fix reductions when applied to zero-length sequences

examples/00_intro_to_thinc.ipynb, thinc/api.py, thinc/backends/__init__.py, thinc/backends/_cupy_allocators.py, thinc/backends/_custom_kernels.py, thinc/backends/cupy_ops.py, thinc/compat.py, thinc/layers/tensorflowwrapper.py, thinc/shims/mxnet.py, thinc/shims/pytorch.py, thinc/shims/pytorch_grad_scaler.py, thinc/shims/tensorflow.py, thinc/tests/backends/test_ops.py, thinc/tests/layers/test_layers_api.py, thinc/tests/layers/test_lstm.py, thinc/tests/layers/test_mnist.py, thinc/tests/layers/test_mxnet_wrapper.py, thinc/tests/layers/test_pytorch_wrapper.py, thinc/tests/layers/test_tensorflow_wrapper.py, thinc/tests/model/test_model.py, thinc/tests/regression/test_issue564.py, thinc/tests/shims/test_pytorch_grad_scaler.py, thinc/types.py, thinc/util.py, website/docs/api-util.md
There are multiple places in the codebase where we attempt to import libraries inside `try...expect` clauses to safely determine their availability. This PR is primarily meant to replace the individual imports with code that calls into a central `compat` module that maintains the imports for all optional libraries.
Additional changes:
* Removal of the `has_cupy` exports from the `cupy_ops`~, `backends` and `api` modules (these were not explicitly exposed to the public API but used internally)~.
* Handle the deprecation of `cupy.fromDlpack` in `cupy >= 10.0.0`.
* ~`util.set_active_gpu` returns `None` when `cupy`/GPU support is unavailable. Prior to this change, the function could potentially raise an unhandled exception if the `cupy` library was not installed.~ `util.set_active_gpu` now …
=> Move compatiblity-related code into a separate `compat` module

thinc/util.py
Otherwise `is_torch_array` does not function correctly.
=> Fix to make 8.0.x pass tests

thinc/backends/cupy_ops.py, thinc/backends/numpy_ops.pyx, thinc/backends/ops.py, thinc/tests/backends/test_ops.py
- Using `{CupyOps,NumpyOps}.adam` with incompatible shapes for weights,
gradients, or moments resulted in out-of-bound writes.
- Using `NumpyOps.adam` with non-float32 arrays resulted filling arrays
with incorrect data.
=> Fix out-of-bounds writes in NumpyOps/CupyOps

thinc/about.py
I thought it would be a good idea to update the version in `master` to 
distinguish it from the v8.0.x branch.
=> Set version to v8.1.0.dev0

thinc/tests/layers/test_pytorch_wrapper.py
Backport #663 to v8.0.x:
This test checked whether the allocator was set to the PyTorch allocator
when the PyTorch shim is used. However, this is not the case when
PyTorch is installed, but CuPy isn't, so the test would fail. Since this
test relies on CuPy, disable it when CuPy is not available.
=> Backport #663 to v8.0.x

thinc/model.py, thinc/tests/model/test_model.py
In the preexisting version of Thinc, `model.copy()` generated separate copies of layers and shims that were used at more than one place in the model structure. This led to inconsistencies e.g. between the outputs of `to_dict()` for the original and the copied models.
This PR creates model copies that preserve object identity between layers.
=> Fix model.copy() bug where layer used more than once

thinc/tests/conftest.py
Ported from [spacy's `conftest.py`](https://github.com/explosion/spaCy/blob/357be2614effdfdff858eca0eb5f17e167ceb265/spacy/tests/conftest.py#L5).
=> Fix for `--slow` CI builds failing

.github/workflows/autoblack.yml, requirements.txt
Ported from [spaCy](https://github.com/explosion/spaCy/blob/master/.github/workflows/autoblack.yml). Also adds the `black` requirement from the former.
=> Auto-format code with `black` + Pin `black` requirement

thinc/shims/shim.py
Moves both volatile reads of the `global_id` global variable into the critical section to prevent a write (from another thread) interleaving them and potentially resulting in multiple `Shim` instances receiving the same ID.
=> `Shim`: Fix potential data race when allocated on different threads

thinc/backends/ops.py, thinc/tests/backends/test_ops.py
- `torch.nn.functional.sigmoid` is deprecated in favor of `torch.sigmoid`.
- Clip `cosh` input in `sechsq` to avoid overflow.
=> Fix two warnings

thinc/tests/backends/test_ops.py, thinc/tests/layers/test_tensorflow_wrapper.py, thinc/tests/model/test_model.py, thinc/util.py
This PR is in preparation of better non-CUDA device support. Once we support non-CUDA GPUs, there may be GPUs available that are not 'CuPy GPUs'. In all places where we use `gpu_is_available` we actually mean: is 'CuPy available with a CUDA GPU'? So, this PR replaces uses of `gpu_is_available` by `has_cupy_gpu`. This allows us to use `gpu_is_available` in the future to check if any GPU is available.
In addition to that, some code had expressions like
```
has_cupy and gpu_is_available()
```
This PR simplify such conditions to `has_cupy_gpu`, since `has_cupy_gpu` implies `has_cupy`.
=> Replace use of gpu_is_available with has_cupy_gpu

thinc/compat.py, thinc/tests/layers/test_basic_tagger.py, thinc/tests/layers/test_mnist.py, thinc/tests/regression/issue519/program.py, thinc/tests/regression/issue519/test_issue519.py
Will leave this in draft mode until `explosionbot` is updated to support the Buildkite thinc slow test suite. 
* explosion/explosion-bot#3
* #672
=> Fixes for slow tests

thinc/tests/backends/test_ops.py
float64 test values close to zero were rounded by conversion to a float32 Torch tensor, resuling in mismatches between Thinc and Torch gradients. This change prevents the loss in precision.
=> test_ops: do not lower precision in conversion to Torch tensor

thinc/util.py
Newer versions of NumPy can expose arrays as dlpack capsules. Use this functionality (when supported) to speed up NumPy -> Torch/Tensorflow array conversion.
=> xp2{tensorflow,torch}: convert NumPy arrays using dlpack

thinc/backends/numpy_ops.pyx
To avoid downstream users from changing the pointers and modifying the behaviour of the struct globally.
=> `NumpyOps`: Do not use global for `CBlas`

thinc/backends/cblas.pxd, thinc/backends/cblas.pyx
When testing #696, we found that adding new `CBlas` methods results in an ABI compatibility. This would mean that every time we add a CBlas method, we also have to rebuild spaCy.
The ABI incompatibility occurs because Cython generates a vtable for `cdef` methods, even when the class or its methods are final. This vtable is used by the caller to look up the (address of) the methods. When methods are added, the vtable of the caller is out-of-sync when the calling code is not recompiled.
This change works around this issue by making the methods of `CBlas` standalone functions.
Many thanks to @shadeMe for discussing the solution space.
=> Make `CBlas` methods standalone functions to avoid using vtables

website/Dockerfile, website/README.md
This Dockerfile was taken from spaCy.
=> Add Dockerfile for building the website

thinc/backends/_custom_kernels.cu, thinc/backends/_custom_kernels.py, thinc/backends/cblas.pxd, thinc/backends/cblas.pyx, thinc/backends/cpu_kernels.hh, thinc/backends/cupy_ops.py, thinc/backends/numpy_ops.pxd, thinc/backends/numpy_ops.pyx, thinc/backends/ops.py, thinc/layers/hashembed.py, thinc/tests/backends/test_ops.py, website/docs/api-backends.md
The HashEmbed layer sums up keyed embeddings. For instance, a key matrix of the shape (50000, 4) will result in 50,000 embeddings, each computed by summing 4 embeddings. The HashEmbed layer computed the embeddings as follows:
```
vectors[keys].sum(axis=1)
```
where `vectors` is an embedding matrix. However, this way of computing embeddings results in very large allocations. Suppose that `vectors` is (4000, 64). Even though the final embedding matrix is (50000, 64), the first expression will construct a temporary array of shape (50000, 4, 64). The overhead is visible in the profile of tok2vec using Thinc `master`:
This change avoids this by introducing a `gather_add` op as a counterpart to `scatter_add`. In this particular example, the `NumpyOps` implementation only allocates the final …
=> Speed up HashEmbed layer by avoiding large temporary arrays

thinc/backends/ops.py, thinc/layers/sigmoid_activation.py, thinc/types.py
Ops used the `FloatsType`, which had `FloatsXd` as its bound. MyPy could not infer that code such as the following is correct,
```
def dish(self, X: FloatsType, inplace: bool = False) -> FloatsType:
tmp = X * X
```
because the inferred type is the union (or a subtype). If we instead constrain the type variable as follows:
```
FloatsType = TypeVar("FloatsType", Floats1d, Floats2d, Floats3d, Floats4d)
```
the type parameter will be instantiated with a single concrete type, solving such issues.
=> Ops: replace FloatsType by constrained typevar

setup.py, thinc/backends/cpu_kernels.hh
`maxout` uses the `argmax` function to determine the index of the maximum value of each `P` inputs. `argmax` uses a generic array loop, which impedes speculative execution and could also prevent unrolling of the outer `maxout` loop.
This change unrolls `argmax` with small values of `P` using a variadic template. This leads to a small performance improvement.
Before this change, `maxout` takes ~3.9% of the runtime:
After this change, `maxout` takes ~2.7% of the runtime:
(The unrolled `argmax` function is no longer a separate unit in the profile.)
=> Unroll `argmax` in `maxout` for small sizes of `P`

website/Dockerfile, website/README.md
This is purely a cosmetic change, but less confusing than thinc-io :).
=> Change Docker image tag to `thinc-ai`

thinc/api.py, thinc/compat.py, thinc/layers/__init__.py, thinc/layers/with_signpost_interval.py, website/docs/api-layers.md
This layer wraps a layer, adding macOS interval signposts for the forward and backward pass. These intervals can then be visualized in the macOS Instruments.app timeline (similar to NVTX ranges work).
Example of Thinc layers that are visualized in the Instruments.app timeline:
=> Add `with_signpost_interval` layer

website/docs/api-loss.md, website/docs/api-util.md
- Remove the note about the expected range (cf. https://github.com/explosion/thinc/pull/707).
- Add the parameter to `to_categorical`.
=> Docs: Fix/update `label_smoothing` description

thinc/api.py, thinc/backends/_custom_kernels.cu, thinc/backends/_custom_kernels.py, thinc/backends/cupy_ops.py, thinc/backends/ops.py, thinc/layers/__init__.py, thinc/layers/dish.py, thinc/tests/backends/test_ops.py, thinc/tests/layers/test_layers_api.py, website/docs/api-backends.md, website/docs/api-layers.md
Dish is a Swish/GELU-like activation function. Since it does not rely on elementary operations like `exp` or `erf`, it can generally be computed faster than Swish and GELU:
https://twitter.com/danieldekok/status/1484898130441166853
=> Add Dish activation

thinc/shims/pytorch_grad_scaler.py
This prevents unnecessary overhead from launching kernels on the GPU in hot backward passes, resulting in sizable savings in training time when training `torch` models.
While training the experimental `CoreferenceClusterer` component with a `Transformer`, this resulted in a 25% reduction in execution time of the `Transformer`'s `finish_update`/backprop pipeline phase.
=> `PyTorchGradScaler`: Cache `_found_inf` on the CPU

thinc/util.py
`tf.experimental.dlpack.from_dlpack` expects a `PyCapsule` object.
=> `util`: Explicitly call `__dlpack__` built-in method in `xp2tensorflow`

website/docs/usage-sequences.md
Update `Ragged` code example in the docs to account for `list2ragged` changes (and fix some `numpy` comparisons that didn't work for me).
Documentation update.
=> Update code example for Ragged

setup.cfg
Closes #747.
I chose to expose `fix_random_seed` from `thinc.api` instead of `thinc.util` because that's where you've stated your public API is consolidated, type definitions in `thinc.types` notwithstanding.
If this isn't something you're interested in, please feel free to close this without merging it.
Thanks for all your work!
=> Register fix_random_seed as a pytest-randomly entry point

azure-pipelines.yml
Until `mypy` 0.980 is released with [this fix](https://github.com/python/mypy/issues/13627), we're disabling the mypy tests on the CI for Python 3.10.
=> disable mypy run for Python 3.10

azure-pipelines.yml
Until `mypy` 0.980 is released with [this fix](https://github.com/python/mypy/issues/13627), we're disabling the mypy tests on the CI for Python 3.10.
=> disable mypy run for Python 3.10 (v9)

requirements.txt
Move `confection` to the section with required explosion packages.
=> Reorder requirements in requirements.txt

requirements.txt, setup.cfg
Adding support for Pydantic 1.10.
=> Support both Python 3.6 and Pydantic 1.10

azure-pipelines.yml
* Run tests with and without extras
* Without: can test with newest versions of `pydantic` and other dependencies
* With: can test `tensorflow`, `torch`, etc. (there is no currently supported version of `tensorflow` that can be installed with the `pydantic` v1.10)
* Remove version restriction for `torch` so that there's an available wheel for all versions of python in the CI
* Add workaround for `tensorflow` for python 3.10 in windows (it appears to be compiled against numpy v1.22 rather than the oldest supported numpy, but since numpy is an optional requirement there's no direct metadata in the package to specify this)
* Update `thinc-apple-ops` steps for current CI jobs
=> Update CI around conflicting extras requirements

thinc/backends/ops.py
Because the stricter type led to mypy failures in spacy, revert the changes for v8.1 and postpone to a later release.
=> Revert return type for Ops.alloc to Any

requirements.txt, thinc/tests/mypy/test_mypy.py
Non-compiled mypy is too slow for practical use in particular in the test suite in the CI. Skipping by whether it's compiled or not becomes easier across a wider range of platforms and python versions than trying to specify it in `requirements.txt`.
=> Skip mypy tests for non-compiled mypy

azure-pipelines.yml, requirements.txt, setup.cfg
* Test `import thinc` before dev requirements are installed.
* Add requirement for `packaging`.
=> Add missing packaging requirement

.github/workflows/autoblack.yml, .github/workflows/explosionbot.yml
This should get rid of the deprecation warnings that have been showing up in our github actions workflows:
=> bump github action versions to deal with deprecation warnings

thinc/backends/ops.py, thinc/tests/backends/test_ops.py
Correct sequence length errors for `reduce_first/last`.
=> Correct sequence length errors for reduce_first/last

thinc/backends/ops.py
The types of primitive sequences passed to the `Ops.asarray*()` methods were mostly incorrect, meaning that the methods could only be used with primitive sequences with a `#type: ignore`.
=> Fix primitive sequence types passed to asarray*()

thinc/backends/cupy_ops.py
[cupy.asarray](https://docs.cupy.dev/en/stable/reference/generated/cupy.asarray.html) only performs a copy if necessary.  However, calling this function here is necessary in case the data had a different format or resided on a different GPU.
=> Update CupyOps.asarray to always copy cupy arrays to the current device

setup.py
`-3` use as command line argument
=> Fix cython directive `language_level`

thinc/api.py, thinc/layers/__init__.py, thinc/layers/with_flatten.py, thinc/layers/with_flatten_v2.py, thinc/tests/layers/test_with_flatten.py, website/docs/api-layers.md
The idea of the `with_flatten` layer is that it flattens a nested sequence, passes it to the wrapped layer, and then unflattens the output of the wrapped layer.
However, the layer was asymmetric in that it passes a list to the wrapped layer, but expects back an XP array. This breaks composition with other Thinc layers, such as `with_array`.
This change makes `with_flatten` symmetric, in that the inputs/outputs of the `with_flatten` and the wrapped layer are symmetric.
It seems that this layer is not used in Thinc or spaCy, so maybe it never worked correctly? At any rate, I needed to flatten a nested list in distillation with `with_flatten(with_array(...))` in distillation and found that it doesn't actually work.
=> `with_flatten`: make the layer input/output types symmetric

thinc/tests/test_util.py, thinc/util.py
The `smooth_one_hot` function in `thinc.util` is being called in the `CategoricalCrossentropy` to apply label smoothing. This PR fixes the check for valid label-smoothing parameter, which was fixed before for `to_categorical`, but not for `smooth_one_hot`. Also added a test for `smooth_one_hot` which was also missing.
=> Smooth one hot fix

thinc/layers/resizable.py, thinc/tests/layers/test_resizable.py
This PR is an attempted fix of the issue outlined in https://github.com/explosion/spaCy/issues/11968. I don't completely understand how the resizable textcat is supposed to work yet, and am not sure if this is the right approach, but locally it got rid of errors and I was able to train a model with reasonable performance.
There are also no tests yet.
=> Make resizable layer work with textcat and transformers

thinc/compat.py, thinc/util.py
`require_gpu` does not distinguish between different failure scenarios, which makes it harder to debug why GPU support is not working. See e.g.
https://github.com/explosion/spaCy/discussions/12410
Rather than raising a generic `No GPU devices can be detected` when CuPy or PyTorch with MPS isn't installed, this change adds more specific errors.
Enhancement
=> Improve exception when CuPy/PyTorch MPS is not installed

thinc/backends/_custom_kernels.cu, thinc/backends/_custom_kernels.py, thinc/backends/cupy_ops.py, thinc/backends/ops.py, thinc/tests/backends/test_ops.py
`Ops.pad` was a fairly slow operation on GPU. It iterates over all sequences and copies each sequence into the padded array. This results in a lot of kernel launches. In the biaffine parser, padding the inputs was more costly than applying the biaffine layers.
This change optimizes the `pad` op using a custom CUDA kernel. The kernel get an array of pointers to the CuPy arrays that are provided as a list. The output array is then filled, parallelizing over the 'time steps'. This should provides the largest amount of parallelism, since we usually have n_steps * hidden_size to parallelize over.
Before:
After:
~**Warning:** please do not review yet! There are still some todo items and I still want to be able to rebase the branch.~
=> Implement `pad` as a CUDA kernel

requirements.txt, setup.cfg, thinc/tests/test_config.py, thinc/tests/test_types.py, thinc/util.py
Allow pydantic v2 using transitional v1 support.
Enhancement?
=> Allow pydantic v2 using transitional v1 support

.github/workflows/tests.yml, examples/00_intro_to_thinc.ipynb, thinc/api.py, thinc/backends/_cupy_allocators.py, thinc/compat.py, thinc/layers/tensorflowwrapper.py, thinc/shims/mxnet.py, thinc/shims/tensorflow.py, thinc/tests/enable_mxnet.py, thinc/tests/enable_tensorflow.py, thinc/util.py, website/docs/api-layers.md, website/docs/api-util.md, website/docs/usage-frameworks.md
Import `mxnet` and `tensorflow` only if explicitly enabled
?
=> Import mxnet and tensorflow only if explicitly enabled

thinc/backends/numpy_ops.pyx, thinc/backends/ops.py, thinc/tests/backends/test_ops.py, website/docs/api-backends.md
Before this change we would fail with an assertion, but it is valid to do reductions over zero-length arrays.
(As long as the length of a sequence is not zero in the case of max and mean, but we check for that separately.)
Bugfix
=> Support zero-length batches and hidden sizes in reduce_{max,mean,sum}

thinc/backends/cupy_ops.py, thinc/backends/numpy_ops.pyx, thinc/layers/strings2arrays.py, thinc/tests/backends/test_ops.py
Always specify `dtype` when creating new arrays so that large integer values are preserved and not at risk of going through an intermediate `float64` conversion.
Bug fix.
=> Preserve values with dtype for NumpyOps/CupyOps.asarray

setup.py, thinc/backends/cblas.pyx, thinc/backends/linalg.pyx, thinc/backends/numpy_ops.pyx, thinc/extra/search.pyx, thinc/extra/tests/c_test_search.pyx, thinc/layers/premap_ids.pyx, thinc/layers/sparselinear.pyx
Profiling support for python 3.12 will not be available for cython 0.29, so toggle internal defaults to be able to disable profiling for python 3.12 completely in `setup.py`. The cython `profile` compiler directive in `setup.py` is then overridden by file-specific or function-specific settings.
* Swap file-specific `profile` settings to `False`
* In setup, set `profile` default to:
* `True` for python < 3.12
* `False` for python >= 3.12
?
=> Redesign cython profile defaults due to python 3.12

thinc/api.py, thinc/layers/__init__.py, thinc/layers/parametricattention_v2.py, thinc/tests/layers/test_layers_api.py, thinc/tests/layers/test_parametric_attention_v2.py, website/docs/api-layers.md
This layer is an extension of the existing `ParametricAttention` layer, adding support for transformations (such as a non-linear layer) of the key representation. This brings the model closer to the paper that suggested it (Yang et al, 2016) and gave slightly better results in experiments.
Feature
=> Add ParametricAttention.v2

thinc/layers/strings2arrays.py, thinc/tests/layers/test_basic_tagger.py
As noted by Daniel in https://github.com/explosion/thinc/pull/917, an error crept in the `forward` function of `strings2arrays`: it shouldn't use `asarray2i` as introduced by #897. The bug at the time wasn't noticed because the slow tests weren't run. For now, this PR also removes the `slow` marker on the basic tagger's `test_small_end_to_end` test, to ensure any regressions would be visible quickly.
bug fix
=> Fix strings2array

.github/workflows/tests.yml, requirements.txt, thinc/backends/cupy_ops.py, thinc/compat.py, thinc/shims/torchscript.py
Reported in #920. Also update MyPy dependency to fix checking of Torch types.
Bugfix.
=> Fix `cupy.cublas` import 

.github/workflows/tests.yml, setup.py, thinc/api.py, thinc/backends/__init__.py, thinc/backends/_accelerate.pxd, thinc/backends/_accelerate.pyx, thinc/backends/apple_ops.pyx, thinc/backends/mps_ops.py, thinc/compat.py, thinc/tests/backends/_apple_blas/test_gemm.py, thinc/tests/backends/test_mps_ops.py, thinc/tests/backends/test_ops.py
This change adds `AppleOps` to Thinc, to ensure that the AMX unit is always used on Apple Silicon Macs. Before this change, a user would get much worse performance if they forgot to install `thinc-apple-ops`.
The `apple_ops` and `_accelerate` modules are built conditionally. When detecting the best CPU implementation, we rely on a `try...except` import to determine whether Apple ops are available.
Even though x86_64 Macs do not have an AMX unit, Accelerate is competitive with BLIS, so it does not hurt to enable Apple ops on all Macs.
Feature
=> Merge `thinc-apple-ops` into Thinc

.github/workflows/explosionbot.yml, .github/workflows/tests.yml, requirements.txt, thinc/tests/test_examples.py, thinc/util.py
- Bump GH actions
- `checkout`: v3 -> v4
- `setup-python` v4: -> v5
- Don't forcefully set `x64` but build for the native platform instead. 
- Update `pytest` to 8.2 and update test accordingly, cf https://docs.pytest.org/en/stable/deprecations.html#pytest-importorskip-default-behavior-regarding-importerror
Bump
=> Bump GH actions

.github/workflows/explosionbot.yml, .github/workflows/tests.yml, requirements.txt, setup.cfg, thinc/about.py, thinc/tests/backends/test_ops.py, thinc/tests/layers/test_linear.py, thinc/tests/test_examples.py, thinc/util.py
Thinc v8.2.4
- Update `typing_extensions` pin
- Update `nbconvert` pin
- Update GH action versions
- Revert `macOS` runner to v13 instead of `latest`
Maintenance & fixes
=> Hotfix v8.2.4

thinc/shims/pytorch.py
update pytorch.py to get rid of torch.cuda.amp deprecated warning.
torch.cuda.amp is deprecated (Pytorch 2.4). This PR updates shims pytorch.py to use torch.amp.autocast instead of torch.cuda.amp.autocast.
replaced _torch.cuda.amp.autocast(self._mixed_precision)_ with _torch.amp.autocast("cuda", self._mixed_precision)_
=> Update torch.cuda.amp to torch.amp in pytorch.py

thinc/shims/pytorch.py
This PR addresses closes #949 by modifying the `default_deserialize_torch_model` function in `PyTorchShim`. The change explicitly sets the `weights_only=True` flag when calling `torch.load`. This resolves the `FutureWarning` regarding potential security issues with implicit pickle module usage and aligns with future PyTorch updates where `weights_only` will default to `True`.
Bug Fix
=> Fix: Explicitly set `weights_only=True` in `torch.load` to handle FutureWarning (#949)

thinc/shims/pytorch.py
PyTorch usage fails with
```
File "thinc/model.py", line 310, in __call__
return self._func(self, X, is_train=is_train)
~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "thinc/layers/chain.py", line 54, in forward
Y, inc_layer_grad = layer(X, is_train=is_train)
~~~~~^^^^^^^^^^^^^^^^^^^^^^
File "thinc/model.py", line 310, in __call__
return self._func(self, X, is_train=is_train)
~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "spacy_curated_transformers/models/with_strided_spans.py", line 108, in with_strided_spans_forward
output, bp = transformer(cast(TorchTransformerInT, batch), is_train=is_train)
~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "thinc/model.py", line 310, in __call__
return self._func(self, X, is_train=is_train)
~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Fix PyTorch autocast/mixed-precision
