MANIFEST.in, bin/cythonize.py, requirements.txt, setup.py
used headers_workaround-free versions of murmurhash and preshed
=> replace headers_workaround

bin/_deserialize.py, thinc/linear/avgtron.pyx, thinc/linear/serialize.pyx
Some fixes that mainly improve the error handling in the Reader.
=> Improve deserialisation

thinc/linear/serialize.pyx
The gain is smaller than for #11, about 15% in total, but still visible.
=> save another call to fread()

thinc/linear/serialize.pyx
Sorry, my fault. `fread()` doesn't set errno, only `fopen()` does. This should work.
=> Fix serialiser

README.rst
=> Fixes typo in README?

README.rst
- The function `backprop_relu` needs the `optimizer` parameter, otherwise the `chain` function does not work.
- Parameter `b` needs to be a 'matrix', so that you can do `Y = W @ X + b`
- The `outer` function (considering it is the numpy version) only works, if `X` and `dY` consist of one training example. With more, i.e. batch learning, `einsum` does column-wise outer product and the sum over these matrices.
- The error for the next step is `dX` in the `backward` function from `create_linear_layer`.
- Finally, some dimensions are wrong and optimizer parameters are fixed
Now you can copy-paste the code examples into a notebook, add a optimizer function, e.g. the `sgd` from `explicit_sgd_update` and run the example.
=> Make the README example executable

setup.py
Fixes a small issue when building from source
=> fix: Setup problem with misppeling open blas arguments

thinc/neural/_classes/hash_embed.py
- Bugfix: Recognize passed seed parameter
- Basis to fix https://github.com/explosion/spaCy/issues/3870
=> Pass seed to init

requirements.txt
=> upgrading pytest to 4.0

requirements.txt, thinc/extra/wrappers.py, thinc/neural/ops.pyx, thinc/neural/util.py
`spacy-transformers` revealed a few bugs in the PyTorch wrapper, especially around saving and loading across GPU and CPU. This PR pulls in those changes, and also simplifies the wrapper classes quite a lot, by introducing new methods that subclasses can customize to control the input and output to and from PyTorch.
=> Improve GPU support and PyTorch wrapper

thinc/neural/_custom_kernels.cu, thinc/neural/_custom_kernels.py, thinc/neural/ops.pyx, thinc/tests/unit/test_ops.py
Past time this embarrassing bug got squashed. This might improve the performance of seq2col on GPU as well.
=> Fix ExtractWindow nW>=2 (closes #47)

thinc/neural/_classes/mish.py, thinc/neural/_custom_kernels.cu, thinc/neural/_custom_kernels.py, thinc/neural/ops.pyx, thinc/tests/unit/test_ops.py, thinc/v2v.py
Mish is a new activation function, a bit like swish. The experiments are pretty convincing and the shape of the activation makes sense.
It's a bit more expensive than ReLU, so I've added CUDA kernels, and implemented an elementwise loop for CPU. I haven't benchmarked those yet, but the speed seems okay.
=> Add mish activation

thinc/neural/_classes/model.py, thinc/neural/optimizers.pyx, thinc/rates.py
Add a grab-bag of new optimizer stuff. Lookahead seems promising, RAdam isn't helping so far (maybe my implementation is bad)?
I got this stuff from folks on the FastAI forum, e.g.: https://github.com/lessw2020/Ranger-Mish-ImageWoof-5
Everything should be disabled by default, so merging should be safe.
=> New optimizer features

thinc/extra/search.pxd, thinc/extra/search.pyx, thinc/extra/tests/c_test_search.pyx
Add destructor handling for Beam, which is required for https://github.com/explosion/spaCy/pull/4686.
=> Add destructor handling for Beam

thinc/tests/unit/test_model.py
=> Revert thread-local ops tests

thinc/linear/linear.pyx, thinc/neural/_classes/affine.py, thinc/neural/_classes/attention.py, thinc/neural/_classes/convolution.py, thinc/neural/_classes/difference.py, thinc/neural/_classes/dropout.py, thinc/neural/_classes/embed.py, thinc/neural/_classes/feature_extracter.py, thinc/neural/_classes/feed_forward.py, thinc/neural/_classes/function_layer.py, thinc/neural/_classes/hash_embed.py, thinc/neural/_classes/layernorm.py, thinc/neural/_classes/maxout.py, thinc/neural/_classes/mish.py, thinc/neural/_classes/model.py, thinc/neural/_classes/multiheaded_attention.py, thinc/neural/_classes/relu.py, thinc/neural/_classes/resnet.py, thinc/neural/_classes/rnn.py, thinc/tests/unit/test_affine.py
Remove the `drop` argument to layers, and instead add a `Dropout` layer.
=> Move dropout to its own layer

README.md
cf title - readme update after PR #117
=> Remove thinc_gpu_ops from install instructions

examples/comparisons/mnist/pytorch_eg.py, examples/comparisons/mnist/thinc_eg.py, examples/scripts/mnist.py, requirements.txt, setup.cfg
Pretty much a drop-in replacement and uses type hints.
=> Tidy up examples and replace plac with typer

examples/howto/type_a_model.py, thinc/model.py
=> Add generic input/output types to Model class

thinc/util.py
fix imports in `prefer_gpu()` and `require_gpu()`
=> fix imports in utils.py

thinc/layers/affine.py, thinc/layers/chain.py, thinc/layers/hashembed.py, thinc/layers/lstm.py, thinc/layers/maxout.py, thinc/layers/mish.py, thinc/layers/recurrent.py, thinc/layers/relu.py, thinc/layers/softmax.py, thinc/model.py, thinc/tests/unit/test_ops.py, thinc/types.py
This can still be refined a little, but this fixes the remaining type errors around the model generics.
I think I've finally understood the `TypeVar` as well. It really is pretty confusing! Also I think it turns out the be important that we've put all our layers in their own files? Using typevars without having module scopes seems really hard.
=> Specify model generics

thinc/layers/__init__.py, thinc/layers/list2array.py, thinc/layers/multisoftmax.py, thinc/layers/siamese.py, thinc/loss.py, thinc/util.py
=> Add/update for spaCy

examples/comparisons/mnist/pytorch_eg.py, examples/comparisons/mnist/thinc_eg.py, examples/model_with_visualization.py, examples/scripts/mnist.py, requirements.txt, setup.cfg, thinc/tests/integration/test_mnist.py
Moved some of the data transforms into [`ml-datasets`](https://github.com/explosion/ml-datasets), which lets us kill a bunch of code in Thinc.
⚠️ You need to upgrade `ml_datasets` locally, otherwise the tests won't pass.
=> Update to new ml_datasets and adjust code

thinc/layers/concatenate.py, thinc/layers/residual.py, thinc/layers/uniqued.py, thinc/model.py
Removing `axis` argument from `hstack` - I don't think that argument is valid? Also, attr `axis` is never defined for the `concatenate` model ?
=> remove axis attr for hstack

examples/basic_pos_tagger_from_config.py
:bug: Fix small misconfigurations in example script.
Just an initial pass that fixes some initial problems detected while using my local branch of Pydantic (with support for generics).
It depends on https://github.com/samuelcolvin/pydantic/pull/1159 merged and released.
There's also a small change to `thinc.model.Model`, I haven't committed it yet, and it might be unnecessary, depending on the end result of the PR in Pydantic.
=> WIP: Fix small misconfigs in example, initial pass

examples/howto/type_chain.py, thinc/backends/ops.py, thinc/layers/cauchysimilarity.py, thinc/layers/concatenate.py, thinc/layers/embed.py, thinc/layers/featureextractor.py, thinc/layers/hashembed.py, thinc/layers/layernorm.py, thinc/layers/linear.py, thinc/layers/list2array.py, thinc/layers/list2ragged.py, thinc/layers/lstm.py, thinc/layers/maxout.py, thinc/layers/maxpool.py, thinc/layers/meanpool.py, thinc/layers/mish.py, thinc/layers/multisoftmax.py, thinc/layers/relu.py, thinc/layers/softmax.py, thinc/layers/staticvectors.py, thinc/layers/strings2arrays.py, thinc/layers/with_list2array.py, thinc/layers/with_reshape.py, thinc/loss.py, thinc/tests/test_types.py, thinc/types.py, thinc/util.py
As discussed with @honnibal, this PR simplifies the `Ints`/`Floats` array distinction and changes them all to `Array`.
=> {Ints|Floats}Xd -> ArrayXd

thinc/backends/ops.py
Add a few cosine helper functions. Not sure about the name for `cosine_abs_loss` as it's kind of confusing with the `cosine_distance` function in `loss.py`
=> add cosine calculations

thinc/backends/ops.py, thinc/model.py, thinc/util.py
- Fix cosine from PR #217
- Add function to change dropout rates across all layers in a model
=> Allow to set dropout rate

thinc/layers/maxout.py, thinc/model.py, thinc/util.py
Some small things I ran into while running code from spaCy.
=> Few small fixes

thinc/layers/chain_module.py, thinc/layers/embed.py, thinc/layers/hashembed.py, thinc/layers/linear.py, thinc/layers/lstm.py, thinc/layers/maxout.py, thinc/layers/mish.py, thinc/layers/recurrent.py, thinc/layers/relu.py, thinc/layers/softmax.py, thinc/layers/sparselinear.pyx, thinc/tests/layers/test_feed_forward.py, thinc/tests/layers/test_hash_embed.py, thinc/tests/layers/test_linear.py, thinc/tests/layers/test_lstm.py, thinc/tests/layers/test_pytorch_wrapper.py, thinc/tests/layers/test_sparse_linear.py, thinc/tests/layers/test_uniqued.py, thinc/tests/regression/test_issue208.py, thinc/tests/test_serialize.py, thinc/tests/util.py
=> Don't auto-init on model creation

examples/00_intro_to_thinc.ipynb
- Added lower bounds for some packages to prevent errors
- Few more print statements that gives the user more of a feel of "something is happening when I execute this cell"
- Fixing GPU execution with `model.ops.asarray` calls. 
- The TF wrapper currently does not converge well 
- The script doesn't actually run yet on GPU, I think because of a bug in thinc that I'm isolating in a different Issue/PR later - cf PR #265
=> Fixes for notebook0

thinc/model.py
:memo: Update docstring for `Model.inc_grad()`
=> Update docstring for Model.inc_grad()

examples/02_transformers_tagger_bert.ipynb, examples/03_pos_tagger_basic_cnn.ipynb, examples/04_configure_gpu_memory.ipynb, examples/04_parallel_training_ray.ipynb, examples/05_benchmarking_layers.ipynb, examples/05_visualizing_models.ipynb, examples/06_predicting_like_terms.ipynb
Notebook on configuring GPU: reduced example to use PyTorch instead of TF
& various other small fixes
=> Fix notebook 04 & 05

examples/00_intro_to_thinc.ipynb
:memo: Add MXNet example to notebook
=> Add MXNet example to notebook

thinc/shims/mxnet.py
:bug: Use MXNet forward reference type to avoid requiring it
=> Use MXNet forward reference type to avoid requiring it

examples/03_pos_tagger_basic_cnn.ipynb
This notebook failed in colab when because it wasn't specifying an Embed column:
```
DataValidationError: 
Data validation error in 'hashembed'
X: <class 'numpy.ndarray'> Y: <class 'NoneType'>
X   wrong array dimensions (expected 1, got 2)
```
=> fix pos tagger notebook by specifying column for embedding layer

examples/06_predicting_like_terms.ipynb
- update to use more specific Int/Float types
- update model to work with more strict data-validation
- define specific model types and use them throughout the example
=> fix and cleanup like-terms notebook

thinc/initializers.py
Cast `scale` to float in `normal_init()` for cupy.
=> Cast scale to float in normal_init() for cupy

thinc/about.py, thinc/api.py, thinc/layers/__init__.py, thinc/layers/softmax_activation.py
- add `softmax_activation` (cf https://github.com/explosion/spaCy/blob/master/spacy/_ml.py#L724)
- bump to 8.0.0a2
=> Add softmax activation

azure-pipelines.yml, thinc/about.py, thinc/neural/_classes/static_vectors.py
Use 0-vector for OOV in StaticVectors
=> Use 0-vector for OOV in StaticVectors

thinc/api.py
=> add to_numpy to thinc's api

thinc/backends/numpy_ops.pyx, thinc/backends/ops.py, thinc/layers/array_getitem.py, thinc/layers/expand_window.py, thinc/layers/hashembed.py
Various checks in case `X` is empty, e.g. in spaCy running with `doc = Doc(vocab, words=[])`
=> robustness against empty X

thinc/about.py, thinc/api.py, thinc/layers/softmax.py, thinc/model.py, thinc/tests/layers/test_layers_api.py, thinc/util.py
- Avoid setting dimensions in `softmax` when not required
- `data_validation` context mananger
- version bump to a21
=> Softmax init

thinc/config.py
Adding few common causes of errors in the config to the error msg
=> Small edit to error msg

thinc/config.py, thinc/tests/test_config.py
Some field names like `validate` are "reserved" and would otherwise shadow `pydantic` attributes. Since we auto-generate schemas based on the signatures of registered functions, this means that a function with an argument `validate` triggers a `NameError`.
This PR adds a mechanism to automatically alias the field names so they're validated and resolved correctly. Field aliases can be arbitrary strings, so I'm currently using the original name plus a space. This means that validation errors referring to those aliased keys still look correct to the user.
=> Add auto-aliases for reserved field names

thinc/tests/layers/test_pytorch_wrapper.py
Fix flaky test by increasing the learning rate - should converge much faster now.
=> Fix flaky test with higher learning rate

thinc/about.py, thinc/api.py, thinc/backends/__init__.py
* introduce method `set_gpu_allocator`
* version bump to 8.0.0a34
=> set_gpu_allocator

thinc/about.py, thinc/model.py
Fixed required to make spacy's pretraining work
+ bump 8.0.0a35
=> fix model.from_dict

thinc/config.py, thinc/tests/test_config.py
Minor improvements to error handling in config.
=> Improve config errors

requirements.txt, setup.cfg, thinc/about.py
=> pydantic upper pin 1.7.0 for now

thinc/util.py
Ensure reproducibility when working with PyTorch models like in `spacy_transformers`.
=> Fix random seed for pytorch

thinc/backends/numpy_ops.pyx
Avoid a more cryptic Cython error downstream
=> check dims before calling blis.gemm

requirements.txt, setup.cfg, thinc/types.py
* Rename `Ragged._cumsums` to `Ragged.cumsums` so it's not flagged as an invalid field.
=> Update for pydantic 1.7 and python 3.9

MANIFEST.in, azure-pipelines.yml, build-constraints.txt, pyproject.toml, setup.cfg, setup.py
* Add `build-constraints.txt` with numpy version pins for building wheels with `pip` and `wheelwright`
* Update setup and version pins
=> Update numpy headers and setup

thinc/backends/numpy_ops.pyx, thinc/extra/tests/c_test_search.pyx, thinc/util.py
Adding sanity checks to avoid 0-length memory allocations
=> Adding a few assert statements for robustness

thinc/layers/parametricattention.py
The `ParametricAttention` layer had fallen behind and wasn't working.
=> Fix ParametricAttention layer

.github/workflows/issue-manager.yml
Adding @tiangolo's issue manager for 'resolved' issues
=> Bot for resolved issues

thinc/backends/__init__.py
In order to detect cases in Jupyter notebooks where `contextvars` are
not preserved across cells, additionally save the ops settings in
thread-local storage as in thinc v7.
The new method `contextvars_eq_thread_ops` returns whether both are the
same ops type. The thread-local storage is not intended for general
use, only for this check in a restricted set of configurations.
=> Add check for contextvars ops vs. thread-local storage

azure-pipelines.yml
This reverts commit fda5e5fa9465671e897b10c894e04cc5e0bd9aa9.
=> Revert "Disable code cov in CI (#476)"

thinc/about.py
=> Set version to v8.0.2

thinc/layers/with_getitem.py
The return value in backprop is pulling from the forward input rather than the backprop input.
=> Fix backprop in with_getitem

thinc/backends/cupy_ops.py
Roughly 25% of GPU time when training a transformer tagger with mixed-precision was spent on computing Frobenius norms for gradient clipping. The reason turns out to be that CuPy only uses a single block for scalar reductions (unless another backend such as CUB is used), resulting in a slow sum reduction when computing a norm.
This change replaces `cupy.linalg.norm` by `cupy.cublas.nrm2`, the optimized cuBLAS implementation for computing l2 norms. This reduces training time about by ~24%.
Top-5 cost before this change:
```
Type  Time(%)      Time     Calls       Avg       Min       Max  Name
GPU activities:   28.49%  23.0423s    185554  124.18us  1.0550us  19.842ms  cupy_sum
5.68%  4.59333s     42324  108.53us  29.151us  2.6026ms  turing_fp16_s1688gemm_fp16_128x128_ldg8_f2f_tn
4.69% …
```
=> Speed up clip_gradient with GPU training

thinc/backends/numpy_ops.pyx, thinc/layers/sparselinear.pyx
For `NumpyOps.hash` and `SparseLinear` replace functions imported from `murmurhash` with inline endian-neutral completely-unrolled versions for uint64 input.
=> Make murmurhash endian-neutral and optimize

azure-pipelines.yml, requirements.txt
cf https://github.com/explosion/spaCy/pull/9873
=> upper pin to mypy

thinc/backends/ops.py, thinc/layers/softmax.py, thinc/tests/backends/test_ops.py, thinc/tests/layers/test_softmax.py, website/docs/api-layers.md
Temperature can be used to change the confidence/entropy of a model.
=> Softmax_v2: add support for softmax with temperature

thinc/backends/_custom_kernels.cu, thinc/backends/_custom_kernels.py, thinc/backends/cupy_ops.py
CUDA kernels for some of the newly-added activation functions.
=> Add kernels for GELU, Swish, and clipped_linear

website/docs/api-backends.md, website/docs/api-layers.md
Documentation updates for changes that I made since the last release.
=> Documentation updates

thinc/tests/test_util.py, thinc/util.py
Also add tests to verify that the n_classes kwarg is correctly checked.
=> to_categorical: permit having one class without label smoothing

README.md, examples/benchmarks/lstm_tagger.py
The example didn't work when I tried running it and this PR fixes it.
=> Lstm benchmark example fix

thinc/backends/ops.py, thinc/layers/sigmoid.py, thinc/tests/backends/test_ops.py
A bit of a follow up to @shadeMe's sigmoid PR: let's check the output against Torch.
=> Check Ops.sigmoid against PyTorch

thinc/backends/numpy_ops.pyx
Remove unused/vestigial functions and re-use existing code.
=> `NumpyOps` cleanup

setup.cfg
=> Fix `fix_random_seed` entrypoint in setup.cfg

thinc/about.py
Prepare for a dev release for the spaCy `v4` branch.
=> Set version to v9.0.0.dev0

requirements.txt
Extend dev requirements for `pytest-cov` and `coverage` to include the most recent releases.
CI/chore.
=> Update dev requirements for pytest-cov and coverage

website/package-lock.json, website/src/styles/box.module.sass, website/src/styles/fonts.sass, website/src/styles/typography.module.sass
This is a super annoying breaking change in SASS (it also happens in `node-sass`/`node-scss`), but there seems to be no way around it.
context: https://sass-lang.com/documentation/breaking-changes/slash-div
- Website build
=> Fixes SASS error

thinc/schedules.py, thinc/tests/test_schedules.py, website/docs/api-schedules.md
This method turns a `Schedule` into a generator by feeding the `Schedule` steps with a given starting step and increment.
Feature
=> Add `Schedule.to_generator`

thinc/about.py
=> Set version to v8.1.7

thinc/about.py
Bump version to v9.0.0dev2.
Maintenance
=> Set version to v9.0.0.dev2

website/gatsby-config.js, website/src/components/layout.js, website/src/styles/base.sass, website/src/styles/fonts.sass
91f4667a511e94e9ac5bd8cb317272cae2bd0517 introduced a hacky solution, that unfortunatly caused the build/dev server to fail, when `/website/src/fonts` doesn't exist. This removes the coupling of `fonts.sass` to other features while keeping it optional.
- Bug fix for local build/dev server
=> Fix brittleness during builds

thinc/api.py, thinc/schedules.py, thinc/tests/test_schedules.py, website/docs/api-schedules.md
This schedule yields values from the wrapped schedule, exponentially scaled by the number of times optimization has plateaued.
Feature
=> Add plateau.v1 schedule

.github/workflows/autoblack.yml
Use `black` version constraints from `requirements.txt` for `autoblack` workflow.
Chore.
=> Use black version constraints from requirements.txt for autoblack

requirements.txt, thinc/mypy.py
=> Extend mypy to v1.0.x

thinc/about.py
=> Set version to v8.1.8

thinc/tests/backends/test_ops.py
Skip `test_lstm_forward_training_fuzz` on aarch64
?
=> Skip test_lstm_forward_training_fuzz on aarch64

thinc/model.py
Found while trying to fix type errors in `spacy-experimental`.
=> Model.begin_update: fix type signature

thinc/about.py
Set version to 8.1.9.
Maintenance
=> Set version to v8.1.9

.github/workflows/tests.yml, azure-pipelines.yml
Allow newest supported torch in extra tests.
CI.
=> CI: Allow newest supported torch in extra tests

thinc/about.py
=> Set version to v9.0.0.dev3

thinc/shims/torchscript.py
Loading a TorchScript model directly onto an MPS device is not supported. So instead, load on CPU first and then move to MPS.
Bugfix
=> Directly loading a TorchScript model onto an MPS device is not supported

.github/workflows/tests.yml
=> CI: Restrict to explosion

thinc/backends/_custom_kernels.py, thinc/tests/backends/test_ops.py
Add a wrapper around `cupy.RawKernel` that lazily compiles them on first invocation.
This prevents CuPy from allocating memory unnecessarily during module init.
Refactor
=> Add `LazyKernel` for lazily-compiled custom `cupy` kernels

requirements.txt, thinc/about.py
=> Set version to v8.1.10

.github/workflows/tests.yml, thinc/tests/backends/test_ops.py
Run basic (numpy-only) tests without warnings.
Tests/CI.
=> Run basic tests without warnings

website/docs/backprop101.md
There is typo in sample code.
Change in documentation
=> Fix typo in example code

.github/workflows/tests.yml
CI: add black/isort/flake8 validate check
Maintenance
=> CI: add black/isort/flake8 validate check

README.md
Switch CI badge to GHA, format.
=> Switch CI badge to GHA

requirements.txt
Update requirements.txt for numpy 1.25, follow-up to #885.
?
=> Update requirements.txt for numpy 1.25

requirements.txt, setup.cfg, thinc/backends/numpy_ops.pyx, thinc/backends/ops.py, thinc/tests/backends/test_ops.py, thinc/tests/test_config.py, thinc/tests/test_types.py, thinc/util.py, website/docs/api-backends.md
Update develop from master for v8.2.
?
=> Update develop from master for v8.2

thinc/about.py
Set version to v8.1.12.
Chore.
=> Set version to v8.1.12

thinc/about.py
=> Set version to v8.2.0

.github/workflows/tests.yml
CI: Add python 3.12.0rc2.
Chore.
=> CI: Add python 3.12.0rc2

setup.cfg, thinc/about.py
Set version to v8.2.1, update for python 3.12.
Chore.
=> Set version to v8.2.1, update for python 3.12

.github/workflows/issue-manager.yml
Update issue-manager version.
Chore.
=> Repo: update issue-manager version

.github/workflows/tests.yml
Use stable python 3.12 and require torch v2.1.1+ for macos extras tests.
Chore.
=> CI: Use stable python 3.12

thinc/about.py
Bump the version to 8.2.2 for the next minor release.
Maintenance.
=> Set version to v8.2.2

thinc/about.py
Set version to v9.0.0.dev4.
Maintenance
=> Set version to v9.0.0.dev4

thinc/about.py
Set the Thinc version to 8.2.3.
Maintenance.
=> Set version to v8.2.3

.github/workflows/tests.yml, requirements.txt, thinc/backends/cupy_ops.py, thinc/compat.py, thinc/shims/torchscript.py, thinc/tests/layers/test_basic_tagger.py
Merge `master` into `v9`.
**Warning:** do not squash.
Maintenance
=> Merge `master` into `v9`

thinc/about.py
Set version to 9.0.0.dev5 (forward-port CuBLAS fix).
Maintenance.
=> Set version to 9.0.0.dev5

thinc/about.py
Set version to 9.0.0.dev6
Maintenance
=> Set version to 9.0.0.dev6

website/docs/api-backends.md, website/docs/api-model.md
Document `AppleOps` and `MPSOps`.
=> Document `AppleOps` and `MPSOps`

thinc/about.py
Set version to 9.0.0
Maintenance.
=> Set version to 9.0.0

.github/workflows/tests.yml, build-constraints.txt, requirements.txt, setup.cfg
Remove support for Python versions prior to 3.9.
=> Remove support for Python versions prior to 3.9

website/docs/api-schedules.md
The table was partly 3 columns and partly 4 columns. Also extend the description of the `scale` argument while at it.
Documentation
=> docs: fix up plateau schedule table

website/docs/api-optimizers.md
Document the `Optimizer.last_score` property. This property was added in Thinc v9, but was not documented.
=> Document the `Optimizer.last_score` property
